### ISSUE TITLE
Show a summary with all materials needed to up tier of character

### ISSUE THREAD

**Issue by AlbertoMonteiro** [tyejae/msf.gg.public#1]
### Actually we already have this: 

![image](https://user-images.githubusercontent.com/836496/41100792-9d2645b0-6a38-11e8-9be2-b4d39f2ca5c3.png)

In this case, to build **Improved Concentration Techniques** I need 3 materials, but each one of those materials, need another material to be assembled.
I need:

- 2 Improved Classified Files
  - Each Improved Classified Files needs
  - 2 Improved Secret Intel
- 4 Improved Skill Focus Catalyst
  - Improved Skill Focus Catalyst needs
  - 2 Improved Focus Catalyst Part
  - 2 Improved Basic Catalyst
- 1 Improved Endurance Program

So I would like to see, that I actually need:

- 4 Improved Secret Intel
- 8 Improved Focus Catalyst Part
- 8 Improved Basic Catalyst
- 1 Improved Endurance Program

And it would be better if, below this info, there is a summary if needed materials for all 6 gears items.

Because Improved Immunity Regimen also needs: 

- 2 Improved Classified Files
- 1 Improved Endurance Program

Now to build those items I need: 

- 8 Improved Secret Intel **Common material**
- 8 Improved Focus Catalyst Part
- 8 Improved Health Catalyst Part
- 16 Improved Basic Catalyst **Common material**
- 2 Improved Endurance Program **Common material**

This would be amazing if I am in a lower tier, and I want to farm those materials buying in stores, to allow me to tier up faster ⚡️

**Comment by tyejae** [comment]
Thank you for submitting a ticket. I took your suggestion and implemented it today. It will be going out in the next code push. We decided to only go down 1 level into the bits needed. So in your example you will now see:
- 2 Improved Classified Files
  - Each Improved Classified Files needs
  - 2 Improved Secret Intel
- 4 Improved Skill Focus Catalyst
  - Improved Skill Focus Catalyst needs
  - 2 Improved Focus Catalyst Part
  - 2 Improved Basic Catalyst
- 1 Improved Endurance Program

We decided against displaying any more data for now, I'll add a new issue to reconsider adding more tiers of information and maybe  total.

**Comment by tyejae** [comment]
Okay I created two other issues based on your feedback. Thanks again, I will be closing this issue as it will be moving out in the next release

**Comment by AlbertoMonteiro** [comment]
Got it, but @tyejae there is any possibility to allow clicking in the first level bits and take us to the clicked material page?

**Comment by AlbertoMonteiro** [comment]
#2 #3 done!!!
