### ISSUE TITLE
Raid Map Creation Is Not Working

### ISSUE THREAD

**Issue by rhamersky** [tyejae/msf.gg.public#100]
Trying to create a lane map for raids for my alliance and there seems to be bugs.

1) I cannot assign a color to a lane (on the right hand side).

2) I cannot hide lanes (option on the right hand side).

3) I cannot clear the colors from the line between nodes even if I remove them the same way I created them.

Any help on this situation would be greatly appreciated.

**Comment by tyejae** [comment]
I cannot recrete this issue. I've tried as **Leader**, **Captain**, and **Member** and I'm able to assign a color to a lane (as a leader or captain) and all other features. If you want, contact me on discord (tyejae#2513) and we can try to work through this.

**Comment by tyejae** [comment]
@rhamersky Not sure if I needed to ping you. Hopefully you see this.

**Comment by tyejae** [comment]
Closing this as the person never responded.
