### ISSUE TITLE
G14 data issues

### ISSUE THREAD

**Issue by stevezel** [tyejae/msf.gg.public#103]
Thanos G13->G14

The upper right and middle right gear are showing as Orange with orange materials but are purple in game.  The name of the materials is correct.  Example, Upper Right shows an Orange Advanced Parchment component, which doesn't exist in game.  Thank you!

**Comment by chronolinq** [comment]
Sabretooth's G13 -> G14. The borders showing are incorrect
msf.gg
![image](https://user-images.githubusercontent.com/11431194/67241784-efb45780-f408-11e9-98e8-c4116481cbb8.png)
in-game
![image](https://user-images.githubusercontent.com/11431194/67241823-0a86cc00-f409-11e9-9d82-98054bbcc8d9.png)

Hovering the items, the items are correct, but it's just the borders that incorrect

**Comment by tyejae** [comment]
![image](https://user-images.githubusercontent.com/6165105/69658843-3ade0d80-103a-11ea-9079-209d6f83e533.png)
Fixed the pips on the frames as well, since I was in the area. I'll be pushing this code out later tonight with the rest of the fixes I'm working on.
