### ISSUE TITLE
Exportable/Shareable teams

### ISSUE THREAD

**Issue by tauna29** [tyejae/msf.gg.public#11]
Be able to export/share teams that you have built.

**Comment by tyejae** [comment]
You can just copy the URL, and paste is anywhere. Is there something more specific you’re looking for?

**Comment by tauna29** [comment]
When I was copy/pasting it to my friend, it comes back with "cannont get characters/build-team/BlackWidow/CaptainAmerica/Hawkeye/IronMan/Quake"

**Comment by tyejae** [comment]
Ahhh I think I may know why. In a couple hours I’ll try something that may
fix that.

**Comment by tyejae** [comment]
This now works! Thanks Tauna
