### ISSUE TITLE
Passive Symbiote synergies not being applied

### ISSUE THREAD

**Issue by varsas** [tyejae/msf.gg.public#115]
When creating teams with Venom and Carnage, their synergies are not coming showing e.g. Carnage's Frenzied Fury on Venom or Venom's Symbiosis on Carnage.
![image](https://user-images.githubusercontent.com/62874741/77889900-8877ba80-7266-11ea-8241-4ff48a9e1b8e.png)

**Comment by tyejae** [comment]
![image](https://user-images.githubusercontent.com/6165105/81128316-b7ccb780-8ef5-11ea-835f-0d0d7e4c6718.png)

**Comment by tyejae** [comment]
All synergies have been redone
