### ISSUE TITLE
Character Selector sorting on Id

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#120]
It looks like the character selector for team creation sorts on Id instead of display name. Noticeable for charachters like Mordo and Miles Morales
![image](https://user-images.githubusercontent.com/11431194/79382401-4c0bb600-7f18-11ea-8e0e-e30e5ee5438a.png)

**Comment by tyejae** [comment]
This one was a bit more of a challenge. But I fixed it. I'm building now and should be live within the hour
