### ISSUE TITLE
Unable to set lanes on Alpha IV

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#122]
Unable to set lanes on Alpha IV for any player
![image](https://user-images.githubusercontent.com/11431194/79628376-4c14dd00-80f5-11ea-8a7e-fa4bd5fdae73.png)

I was able to claim a lane using the bot however on this map. Other maps I was able to set lanes in msf.gg just fine.

**Comment by tyejae** [comment]
This has been fixed. THanks as always Chronolinq
