### ISSUE TITLE
War defense roster is empty

### ISSUE THREAD

**Issue by szabieable** [tyejae/msf.gg.public#123]
My roster is filled properly but on war defense screen there is no choiceable character at all
![image](https://user-images.githubusercontent.com/35137198/79847757-74842c00-83c0-11ea-9592-cdd689439d1f.png)

I have a really old registration, tried with chrome / safari but the result is same.

Solved the issue with a new registration

**Comment by szabieable** [comment]
Okay after a deeper investigation the only difference in the response for the getRoster call is:
my old account have an entry for Greg

**Comment by tyejae** [comment]
This should be resolved
