### ISSUE TITLE
AIM Infector added to roster post MSF Tools Import

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#133]
Not sure where this guy came from

![image](https://user-images.githubusercontent.com/11431194/80536558-681b4880-8957-11ea-9565-5b7611854d2d.png)

**Comment by tyejae** [comment]
So MSF Tools is actually populating some characters not in game. In this case Beast. I need to reject those characters. If it doesn't find a valid character you'll get a greyed out aim infector.

**Comment by msftools** [comment]
I think this is fixed already?

**Comment by tyejae** [comment]
Yeah you're right, it was a faulty import
