### ISSUE TITLE
Server Time

### ISSUE THREAD

**Issue by Matatsuo** [tyejae/msf.gg.public#14]
You seem to use local time on your counters on the home page. If you could change them to server time it would be very appreciated

**Comment by tyejae** [comment]
What server time are you referring to? We use the browsers local time because we are assuming that you are accessing your browser in the timezone that you're playing in.

**Comment by Matatsuo** [comment]
![timers](https://user-images.githubusercontent.com/19157447/42539630-caea11ee-84ef-11e8-92ba-7943e47bfd2a.png)

The timers you see here are based on local time so they are incorrect compared to in game timers, my timezone is NZST which is +12 hours so the actual timers should be: next free energy in 14 hours and reset in 2 hours

**Comment by tyejae** [comment]
Ahhh, I’ll have to see if I can get a list of all the servers reset times.
Thanks for the info!

**Comment by tyejae** [comment]
We are abandoning the timer.
