### ISSUE TITLE
Issue with room placement on war layout

### ISSUE THREAD

**Issue by Godimhard** [tyejae/msf.gg.public#141]
I'm trying to move bridge but it keeps moving it to a different place even after saving it. I can move it somewhere else and it saves that but when I'm trying to put it where it should go it just doesn't save the change?

**Comment by tyejae** [comment]
@Godimhard Can you show me a screenshot of your positions. And where exactly you are moving it to? I will attempt to recreate and fix it.

**Comment by Godimhard** [comment]
Ok so the first image is how i want it, I click done and then when i go back to it it looks like the second pic. it keeps putting cargo above bridge for some reason.
![war set up 1](https://user-images.githubusercontent.com/64788811/80981723-440daa80-8e22-11ea-998b-a82b1285e88b.png)
![war set up 2](https://user-images.githubusercontent.com/64788811/80981729-453ed780-8e22-11ea-98eb-2bcd22cdb9cf.png)

**Comment by Godimhard** [comment]
ok so the first image is how i want it. I click done but when i go back it looks like the second image it keeps putting bridge above cargo for some reason?
![war set up 1](https://user-images.githubusercontent.com/64788811/80981857-6e5f6800-8e22-11ea-9423-05e0c2bf9d46.png)
![war set up 2](https://user-images.githubusercontent.com/64788811/80981861-6f909500-8e22-11ea-8740-51a3e4dd25cc.png)

**Comment by Godimhard** [comment]
any updates on this? dont want to leave my war defence up here for too long is all

**Comment by tyejae** [comment]
@Godimhard I'm working it currently

**Comment by tyejae** [comment]
@Godimhard Try it now.
