### ISSUE TITLE
Speed turn comparer

### ISSUE THREAD

**Issue by AlbertoMonteiro** [tyejae/msf.gg.public#15]
It would nice to have a feature that you can build your team and enemy team and see the turn list, an entire list of 10 characters who is going to attack first.

## For example

With those squads I would like to see:

![screenshot_2018-08-08-10-04-34](https://user-images.githubusercontent.com/836496/43838700-7dcdb186-9af2-11e8-8df1-ba9369695fd8.png)

1. **[Team 1]** Korath the Pursuer		- Speed: 114
1. [Team 2] Yondu					- Speed: 112
1. **[Team 1]** Deadpool					- Speed: 112
1. [Team 2] Nebula					- Speed: 107
1. [Team 2] Hand Sorceress			- Speed: 105
1. **[Team 1]** Wolverine				- Speed: 095
1. [Team 2] Wolverine				- Speed: 095
1. [Team 2] Luke Cage				- Speed: 080
1. **[Team 1]** Kingpin					- Speed: 075
1. **[Team 1]** Hulk						- Speed: 065

**Comment by tyejae** [comment]
We've decided this isn't something we will focus on for now. We plan to implement a table with stats in it which would essential be able to deduce this result.

**Comment by AlbertoMonteiro** [comment]
But the UX for this would not be good, because I have to calculate that

Strikeforcelabs already show that, and its not that straightforward, but no problem
