### ISSUE TITLE
Raid map lanes drawing extra lines

### ISSUE THREAD

**Issue by societysCatalyst** [tyejae/msf.gg.public#153]
![image](https://user-images.githubusercontent.com/3135669/81878131-17aa0a80-9555-11ea-9b4f-b264c23f0329.png)
![image](https://user-images.githubusercontent.com/3135669/81878152-301a2500-9555-11ea-8692-7fd1df3e5f7c.png)
Was filling in lanes for u7. Had them all setup how we wanted them. But when you copy to other teams, or leave and navigate back, there are the extra lines you see in the second screen shot. It's MUCH worse in Alphas, I had the standard 8 lanes drawn out, and now they are all over the place splitting off in multiple directions:
![image](https://user-images.githubusercontent.com/3135669/81878357-cea68600-9555-11ea-9da0-32711c6df8ce.png)

**Comment by societysCatalyst** [comment]
![image](https://user-images.githubusercontent.com/3135669/81879150-ef6fdb00-9557-11ea-8691-4c646d419af5.png)
all of these errors from trying to delete 1 of the extra lines

**Comment by societysCatalyst** [comment]
![image](https://user-images.githubusercontent.com/3135669/81879618-49bd6b80-9559-11ea-822d-7ffe48d11bb9.png)
looks like it is drawing way too many lines.

when i click once, it draws the line fine without errors. when i click again to change its direction, i get 1 error like above where it fails to delete the line. and then when i open a map that has bugged lines, i get this error:
![image](https://user-images.githubusercontent.com/3135669/81880277-1c71bd00-955b-11ea-9d95-069d07f1bf05.png)

**Comment by tyejae** [comment]
What the problem ended up being was two fold:

1. Was incorrectly adding lines more than once
2. People were adding new lines while old lines were still being deleted which was causing lines not to be deleted properly

Ultimately I just put a loader when deleting a raid line. It allows for the save/delete to happen before the user can move on. 

Will be live when I update the site next.
