### ISSUE TITLE
War Defense Management

### ISSUE THREAD

**Issue by nemato1** [tyejae/msf.gg.public#155]
It would be ideal for Leaders and Captains to be able to set the War Defense of the teams in the alliance. Not everyone is as willing to utilize every part of the site, however when we run commands with the bot some of their teams should be hidden. If their roster is added and we had the capability to edit their defense for them to eliminate confusions with the Alliance Counters. In addition, it would also be helpful if we were trying to assist someone with a better layout for their defense in game, we could show them how we would strategize their roster on the site, then they could mirror it in game.

**Comment by tyejae** [comment]
This is now done!
