### ISSUE TITLE
war used command invalid results

### ISSUE THREAD

**Issue by bridgetemichelle** [tyejae/msf.gg.public#159]
See Results:
![war used results issue](https://user-images.githubusercontent.com/65606277/82331740-60205880-9999-11ea-8977-ad77310d727c.png)

**Comment by tyejae** [comment]
Those look correct to me, if you are trying to mark asgardians used. You'd type `~w used asg`

**Comment by bridgetemichelle** [comment]
Not tried to criticize, but if I enter the wrong code, would be nice if I got a reply that I entered the wrong code, instead of finding the closest match.  I guess that's what it's doing?    So I used incorrect team repeatedly,  but get a response instead of an error message.
