### ISSUE TITLE
My Teams Shuffling Teams

### ISSUE THREAD

**Issue by tyejae** [tyejae/msf.gg.public#168]
![image](https://user-images.githubusercontent.com/6165105/82921242-04237a00-9f2d-11ea-8d35-f33952497743.png)

**Comment by chronolinq** [comment]
Before edit:
![image](https://user-images.githubusercontent.com/11431194/82968181-8dfd3280-9f81-11ea-9c9f-6e8aae523110.png)

After edit:
![image](https://user-images.githubusercontent.com/11431194/82968216-a40af300-9f81-11ea-84d7-9806a64d8354.png)

The team order does not stay that way if I refresh the page. However if I make another edit, the team order is saved how it appears.

**Comment by nemato1** [comment]
I would like to add to this since it is also in reference to editing teams. If you change out one character it deletes the power of the team, and only says the power of the new toon.

**Comment by nemato1** [comment]
Original Team:
![Screenshot 2020-06-14 at 7 10 53 PM](https://user-images.githubusercontent.com/64911130/84606312-1ed57880-ae73-11ea-9014-443b2dc3cbf2.png)

Taking out 1 character:
![Screenshot 2020-06-14 at 7 11 10 PM](https://user-images.githubusercontent.com/64911130/84606322-344aa280-ae73-11ea-9924-752335ee7a04.png)

Adding in 1 new character:
![Screenshot 2020-06-14 at 7 11 44 PM](https://user-images.githubusercontent.com/64911130/84606331-42002800-ae73-11ea-988e-3934d238e283.png)

Only shows the power of Nebula for the whole team even after saved:
![Screenshot 2020-06-14 at 7 15 01 PM](https://user-images.githubusercontent.com/64911130/84606354-6f4cd600-ae73-11ea-997b-c22965cdfc23.png)

**Comment by tyejae** [comment]
@nemato1 @chronolinq I've been trying for over an hour to recreate this. Even created a bunch of teams with an ordered team name so that I could easily see if it's changed. I cannot for the life of me make it mix up the order

![image](https://user-images.githubusercontent.com/6165105/86521305-bccdba80-be03-11ea-9022-e9f0702f8420.png)

**Comment by chronolinq** [comment]
@tyejae Might be able to close this as OBE. I tested this the other day and it seems fine

**Comment by tyejae** [comment]
Thanks @chronolinq
