### ISSUE TITLE
Customizable route colors for raids

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#17]
Some of the colors on the raid routes are kind of hard to read. I can also imagine that color blind users will also need special colors.

Would be great if if there was a way to customize the colors to a hex value.

If that is too difficult, applying the colors with a class style vs inline style would make it easier for someone to change via the inspector

**Comment by tyejae** [comment]
Yeah I think this is important too. For the short term, I'll change it to use a CSS class. So that it can be changed easily. And I'll create an enhancement on our internal backlog to allow for entering custom colors.

**Comment by chronolinq** [comment]
Sounds great. This can get closed when the CSS classes get added!

**Comment by chronolinq** [comment]
Not sure if related, but it appears that I can't mark routes in certain directions now.

e.g. C5 on En Fuego, I cannot mark a route going east with blue

**Comment by tyejae** [comment]
It was related, fixed it and will be out on the site later today. Thanks!

**Comment by chronolinq** [comment]
Thanks for the changes!

By the way, these are the colors I was playing around with:

#f83c46 - Red
#fffd30 - Yellow
#525afb - Light Blue
#ffffff - White
#913afb - Purple
#90ec8b - Light Green
#fa981d - Orange
#00a3a3 - Teal

I tried to get AAA ratings via: http://jxnblk.com/colorable/demos/text/ but I settled on AA on a couple colors so that they wouldn't all look like white
