### ISSUE TITLE
msf.gg and discord connection does not hold.

### ISSUE THREAD

**Issue by lechter69** [tyejae/msf.gg.public#170]
Good morning,
      For a few days I have been trying to  use the msf.gg bot and  toolbot. I link to discord through the settings and authorize msf.gg on my account. it advises i have no roster saved, though it shows on the site, and the link is not connected when I open the msf.gg settings tab back up after authorizing it. In discord it shows msf.gg as an authorized app. 
Not sure what else i need to do.

**Comment by tyejae** [comment]
@lechter69 Thanks for reporting. Can you let me know what browser you are using? Also if you have Discord, please PM me your MSF.gg username so I can look you up. My contact on Discord is tyejae#2513

**Comment by xjcomer7** [comment]
@tyejae i'm having the same issue over the last week for five of my alliance members. Is there something I can do to fix this? The connection wont hold over microsoft edge, google chrome nor my mobile safari

**Comment by xjcomer7** [comment]
also @lechter69 to PM tyejae its case sensitive so friend request TyeJae#2513

**Comment by tyejae** [comment]
For xjcomer7 it was user error. And I haven't gotten a response from @lechter69, so I'm closing this issue.
