### ISSUE TITLE
Download Maps Broken

### ISSUE THREAD

**Issue by tyejae** [tyejae/msf.gg.public#173]
![image](https://user-images.githubusercontent.com/6165105/83195142-9c1c9180-a0ee-11ea-9405-c973d6e02712.png)

**Comment by chronolinq** [comment]
![image](https://user-images.githubusercontent.com/11431194/83978951-ce34ad00-a8bf-11ea-97cd-df51ed608990.png)

**Comment by tyejae** [comment]
This is fixed
