### ISSUE TITLE
Alliance not deleted when last member/owner leave

### ISSUE THREAD

**Issue by adrien63190** [tyejae/msf.gg.public#175]
I just create an alliance "French Ragnarok" in msf.gg but I want leave it because I am not the owner in-game but when I leave, I just discover that the alliance wasn't deleted and I am still consider as leader in alliances view/apply menu but I can't access on it. Can you deleted it or send me back in it.

**Comment by tyejae** [comment]
Leaving an alliance as the leader will now delete the alliance and remove all the members. I saw you are in the alliance again @adrien63190, so I didn't delete the alliance. Please hit me up on Discord if you have any more questions. My discord ID is tyejae#2513
