### ISSUE TITLE
Stats table background color on hover

### ISSUE THREAD

**Issue by jfranger** [tyejae/msf.gg.public#178]
Hey there, the mouse hover on the even rows or

.table.is-hoverable.is-striped tbody tr:not(.is-selected):hover:nth-child(2n) {
    background-color: #f5f5f5;
}

is basically the same bg color as the text color (#eee), making it impossible to read. I suggest the same color as the other rows, or #4f7895 - it looks just nice and clean.

**Comment by tyejae** [comment]
Thx @jfranger this should be an easy one to change

**Comment by tyejae** [comment]
This is fixed, and will be live when I make the next publish
