### ISSUE TITLE
Alliance Raid Maps displaying Username

### ISSUE THREAD

**Issue by Nietzsche17** [tyejae/msf.gg.public#179]
Raid maps are displaying username instead of display name. Edit: It appears it is not just the raid maps.

**Comment by tyejae** [comment]
@Nietzsche17 Is this the bot or the site? Can you also provide a screenshot

**Comment by tyejae** [comment]
@Nietzsche17 Hopefully you see this message. I'm still looking for more information so I can fix this. Can you provide a screenshote?

**Comment by tyejae** [comment]
Well I haven't gotten a response in 3 weeks after multiple requests for feedback. I don't see this behavior.
