### ISSUE TITLE
El Scorcho Raid

### ISSUE THREAD

**Issue by ThePhatKat** [tyejae/msf.gg.public#18]
Lane 2 is listed as City (heroes only) when it's actually just city.

**Comment by tyejae** [comment]
I'm aware that the game shows CITY or GLOBAL for some nodes, but the code indicates hero in the ID. So I assumed it was hero only as well. Can you verify that you can use heroes and villains?

**Comment by tyejae** [comment]
For example:
'Merica in game says ONLY GLOBAL CHARACTERS but the ID says ID_REQUIRES_HEROES_GLOBAL
I think you may be right, I just want to confirm.

**Comment by tyejae** [comment]
Again I think you're right, so I've change it to this:

![image](https://user-images.githubusercontent.com/6165105/44608175-b1d98600-a7a7-11e8-846b-4a5e607f15dd.png)

**Comment by tyejae** [comment]
This is fixed now
