### ISSUE TITLE
Discord problem 

### ISSUE THREAD

**Issue by dzsano88** [tyejae/msf.gg.public#182]
Hy.. I have some problem with the discord.. First I forgot my password on the msf.gg... I would like a new password but I can't get email or nothing so I couldn't do that.. That is why I made a new login.. Everything was fine except I couldn't connect with my discord... When I try that it's gonna success but after a few seconds it's fail and I get a page when I could join to discord again... And always do that.. So I need some help for this thx

**Comment by tyejae** [comment]
@dzsano88 Contact me on Discord and I'll fix it for you. Here is the invite to the server: https://discord.gg/u9pYqpJ
Look me up TyeJae#2513

**Comment by dzsano88** [comment]
Thx you did that on last week :) so now everything is OK! :)

Hódosi János

tyejae <notifications@github.com> ezt írta (időpont: 2020. jún. 30., K
16:25):

**Comment by tyejae** [comment]
ok thanks, I'll close this
