### ISSUE TITLE
Site-Suggestion: Make teams able to be moved to a specified folder.

### ISSUE THREAD

**Issue by d90** [tyejae/msf.gg.public#183]
As the title suggests, it would be nice if we can get basic move operations for teams. Ability to move them, or even copy from folder to folder instead of deleting and creating over and over.

**Comment by tyejae** [comment]
You can now move/copy teams to other folders (when I publish next)
![image](https://user-images.githubusercontent.com/6165105/86519684-fac1e300-bdf1-11ea-8c81-87b8cec9bb04.png)
![image](https://user-images.githubusercontent.com/6165105/86519687-06ada500-bdf2-11ea-8f37-77811a8fe851.png)
