### ISSUE TITLE
Site-Suggestion: Rotate equipped slots in character dialog

### ISSUE THREAD

**Issue by enigmaticaljedi** [tyejae/msf.gg.public#185]
Currently the slots are arranged horizontally:

|Slot 1|Slot 2|Slot 3|
| --- | --- | --- |
|Slot 4|Slot 5|Slot 6|

This makes it difficult to transpose from the game to msf.gg as the slots in the game are arranged vertically:

|Slot 1|Slot 4|
| --- | --- |
|Slot 2|Slot 5|
|Slot 3|Slot 6|

I suggest that the dialog for ticking these slots for a given character is changed to represent them vertically to make it easier to copy between the game and the website

**Comment by tyejae** [comment]
This is done and will be live the next time I publish
![image](https://user-images.githubusercontent.com/6165105/86516835-b7a74600-bdd8-11ea-9ff4-67196cca805d.png)
