### ISSUE TITLE
Personal Roster Filter shows Asgard as an Origin

### ISSUE THREAD

**Issue by d90** [tyejae/msf.gg.public#188]
Steps to reproduce: 
1. Log into msf.gg
2. Click roster
3. Click roster filter

Asgard is listed alongside City, Cosmic, and global
![image](https://user-images.githubusercontent.com/10871791/86392809-0c787e80-bc6a-11ea-96e7-8e08e58a145d.png)

**Comment by tyejae** [comment]
This will be listed under team shortly, i made the fix. And when the next build goes out, it'll be live
