### ISSUE TITLE
Strike Command Recommendations

### ISSUE THREAD

**Issue by d90** [tyejae/msf.gg.public#189]
`~strike log` 
Current Action: Lists all strikes for all members of discord server
Proposed Action: List only strikes for Current Alliance
Scope: Leader\Captain

`~strike log alliance`
Current Action: Lists strikes for current alliance
Proposed Action: Remove command
Scope: Leader\Captain

`~strike log full`
Current action: None
Proposed Action: List all strikes for all members of discord server
Proposed Scope: Server admins

**Comment by tyejae** [comment]
I am going to close this here, and move it to the #bot-backlog and the private bot backlog. Excellent idea and I'll implement it soon!
