### ISSUE TITLE
Deflect description missing and image incorrect

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#19]
![image](https://user-images.githubusercontent.com/11431194/44600745-16d4b200-a78f-11e8-8988-4dc278f5e410.png)

Also I believe the evade icon changed in the last patch?

**Comment by tyejae** [comment]
Thanks, I'll put this on the radar. Appreciate your keeping us straight! :D

**Comment by chronolinq** [comment]
Description for Deflect looks good now, just needs the icon.

Unfortunately by getting the descriptions from the game data, we lose fidelity on bleed damage percentages :(

**Comment by tyejae** [comment]
Yeah, I wondered if it was worth it. But thought having it pull directly
from the data files was better for the overall consistency of the site. And
removes a manual step!

**Comment by chronolinq** [comment]
Finally. I can use the site now ;)
