### ISSUE TITLE
SSM Assist/Counter Info Doesn't Match Basic

### ISSUE THREAD

**Issue by NobleDeen** [tyejae/msf.gg.public#199]
The basic level 6 for SSM shows his assist gives defense down for 2 turns, but his basic only gives defense down for 1 turn
![Clip_2](https://user-images.githubusercontent.com/68476897/87858557-b27be800-c8fc-11ea-898d-4df864c1af5d.jpg)

**Comment by tyejae** [comment]
So the datamine is showing that level 6 assist/counter **does** have 2 turns of defense down applied. I'll paste the json in there. I double checked on MSFTools as well and he also is showing the same

```json
					{
						"action": "proc",
						"procs": [
							{
								"proc": "DefenseDown",
								"spawn_pct": [
									25,
									25,
									50,
									50,
									50,
									100,
									100
								],
								"use_count": [
									1,
									1,
									1,
									1,
									1,
									2,
									2
								]
							}
						]
					}
```

**Comment by NobleDeen** [comment]
Interesting behavior. Thanks for following up on this!
