### ISSUE TITLE
Character Gear Tier Screen Show Total Bits Needed For Upgrade

### ISSUE THREAD

**Issue by tyejae** [tyejae/msf.gg.public#2]
For example
- 2x Improved Classified Files
  - Needs 2x Improved Secret Intel
- 4x Improved Skill Focus Catalyst
  - Needs 2x Improved Focus Catalyst Part
  - Needs 2x Improved Basic Catalyst
- 1x Improved Endurance Program

Show a total like:
- 4x Improved Secret Intel
- 8x Improved Focus Catalyst Part
- 8x Improved Basic Catalyst
- 1x Improved Endurance Program

**Comment by AlbertoMonteiro** [comment]
Amazing!! Done!!
![image](https://user-images.githubusercontent.com/836496/41154755-94b7451e-6af1-11e8-9c19-2a1eceb776ca.png)
