### ISSUE TITLE
Suggestion: Show node id on hover and raid node detail page

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#20]
Would be useful to see the Id of the node on hover and on the raid detail page. e.g.

![image](https://user-images.githubusercontent.com/11431194/44746738-0b032b80-aac0-11e8-883f-3240d71c75ab.png)

![image](https://user-images.githubusercontent.com/11431194/44746805-3b4aca00-aac0-11e8-99a6-a33e2c52702d.png)

**Comment by tyejae** [comment]
Yes! Because when someone tells me the name of the node, i have to hunt for
it. Good idea

**Comment by chronolinq** [comment]
Looks good! Thanks for the quick turn around
