### ISSUE TITLE
Alliance TCP and STP Sorting

### ISSUE THREAD

**Issue by nemato1** [tyejae/msf.gg.public#200]
When viewing your alliance page, the TCP and STP sorting is not based on the full value, it appears to be only based off of the first number in the given value. 40k will appear higher than 300k. 900k will show higher than 1 million.

![Screenshot 2020-07-19 at 1 40 34 PM](https://user-images.githubusercontent.com/64911130/87881197-aad44600-c9c5-11ea-8cd7-993eed6fc83d.png)
![Screenshot 2020-07-19 at 1 39 16 PM](https://user-images.githubusercontent.com/64911130/87881198-ab6cdc80-c9c5-11ea-9f3b-ebfe3c806416.png)

**Comment by tyejae** [comment]
This works now. Try it out @nemato1
