### ISSUE TITLE
In Character page, Gear Inspector section text is wrong/unclear

### ISSUE THREAD

**Issue by maxilapo** [tyejae/msf.gg.public#202]
![image](https://user-images.githubusercontent.com/3606588/87951368-7a001980-ca76-11ea-8082-99b8a90caf53.png)

See screenshot above (From Thor page). The gear shown here is actually the gear taken to go from T13 to T14 (If I understand well) when the text say "Mats required for T13."

So I have propositions to improve this section:

1- Change the text for "Mats required to passe from T13 to T14"
2- Put a section for Gold Gear required for T13 and one for T14
Put a section with all the gear necessary for T1 to T14

Thank you

**Comment by tyejae** [comment]
This will be live shortly
![image](https://user-images.githubusercontent.com/6165105/88984396-544aef80-d282-11ea-82ea-840323322351.png)

**Comment by maxilapo** [comment]
Nice update guys!

Thanks for the good work!
