### ISSUE TITLE
8 digit CPs not sorting

### ISSUE THREAD

**Issue by El-Presidente-msf** [tyejae/msf.gg.public#205]
(https://media.discordapp.net/attachments/697807149237272577/735503299410919556/IMG_2727.PNG)

**Comment by tyejae** [comment]
This is fixed! I fixed all the columns.

![image](https://user-images.githubusercontent.com/6165105/88984089-945da280-d281-11ea-87f9-3363aa94d924.png)
![image](https://user-images.githubusercontent.com/6165105/88984105-9b84b080-d281-11ea-9595-0efb56230951.png)
