### ISSUE TITLE
[IDEA] Number of People In Alliance

### ISSUE THREAD

**Issue by nemato1** [tyejae/msf.gg.public#206]
It would be helpful to show the number of people currently in the alliance on the site. I have attached a screenshot with a little edit to show what it could look like.

![Screenshot 2020-07-22 at 9 42 31 PM (1)](https://user-images.githubusercontent.com/64911130/88245812-83e86f00-cc66-11ea-93ff-69b151d2fb30.png)

**Comment by tyejae** [comment]
This will be live soon

![image](https://user-images.githubusercontent.com/6165105/88984829-932d7500-d283-11ea-8ca3-bcbf1f53b8d1.png)
