### ISSUE TITLE
Some Raid Pages are not working

### ISSUE THREAD

**Issue by KainJourney** [tyejae/msf.gg.public#21]
I can't seems to open some of the raid page for example 
https://msf.gg/raids/raid_lvl_65/I4/raid_ult06_15
https://msf.gg/raids/raid_lvl_65/H5/raid_ult06_mb08

the raid mob doesn't load out?

**Comment by tyejae** [comment]
Thanks! I’ll look into k into these as soon as I can

**Comment by tyejae** [comment]
This is now resolved
