### ISSUE TITLE
Flavor Tags

### ISSUE THREAD

**Issue by nemato1** [tyejae/msf.gg.public#217]
Supernatural, Symbiote, Power Armor, and Young Avengers are listed under Flavor tags and should probably be under Teams.

![Screenshot 2020-08-03 at 8 32 08 PM](https://user-images.githubusercontent.com/64911130/89240103-1c68e280-d5c9-11ea-81ba-695512827809.png)

**Comment by tyejae** [comment]
This is done, will be live soon.
