### ISSUE TITLE
Ability to download Jason or xls of my alliance

### ISSUE THREAD

**Issue by mwalkerpear** [tyejae/msf.gg.public#218]
As an Alliance manager, I’d like to be able to download either Jason or XLS of my alliance data, specifically from this summary page:

https://msf.gg/alliance/id/5f137aa6312ae/members

![IMG_0660](https://user-images.githubusercontent.com/49661118/89738752-fa8bb780-da2f-11ea-943c-cebac1797caa.png)

**Comment by tyejae** [comment]
This is done.
![image](https://user-images.githubusercontent.com/6165105/90140420-9702d200-dd2e-11ea-9811-773a26f3d886.png)

I'll be publishing it shortly. Thanks for the request @mwalkerpear

**Comment by mwalkerpear** [comment]
That's awesome!  Thank you so much
