### ISSUE TITLE
Black Order team not appearing in counter

### ISSUE THREAD

**Issue by mapludy** [tyejae/msf.gg.public#219]
Hello 

I have an issue where my Black Order team does not appear in the recommended counters in MSF.gg bot.

I've tried updating individual characters at MSF.PAL.GG, and at MSF.GG. Unlinked and Linked the accounts to discord to no avail. 

Do you have any suggestions how I might be able to resolve this?

![image](https://user-images.githubusercontent.com/69480243/89821970-4dcf3a00-db04-11ea-9952-8ae577f786c9.png)

![image](https://user-images.githubusercontent.com/69480243/89822132-8c64f480-db04-11ea-920d-28fb3c3d7b44.png)

**Comment by d90** [comment]
The bot reads your available counters from the roster you have, with predefined teams that are submitted through a separate war counter system. The website's "teams” feature does not link in with the war counter feature. Based on your screenshots the bot is working the way it's supposed to.

**Comment by mapludy** [comment]
Thank you for your quick response. As it turns out, I had inadvertently set
the team on war defense, and removing the team from defense fixed it.

Cheers
