### ISSUE TITLE
Ultimus Raid V v2 lane error

### ISSUE THREAD

**Issue by AteAllTheCookie** [tyejae/msf.gg.public#22]
It seems there are a few extra lines on the Ultimus Raid V v2 raid map. For example H3 does not connect to H4. But, on the MSF.gg raid map it shows a connection path between the two nodes.

Here are all the nodes that seem wrong
B3->B4
C4->C5
G4->G5
H3->H4

Not sure If I am just doing something wrong. Thanks for all the hard work, it has really helped playing through the game.

**Comment by tyejae** [comment]
This is now fixed. Thanks for pointing this out.
