### ISSUE TITLE
Strike Command Recommendation: Prune

### ISSUE THREAD

**Issue by d90** [tyejae/msf.gg.public#225]
I propose adding functionality to prune strikes based on a user defined variable. For example where x  is the minimum days old a strike should be to remove. I imagine this to be run ad-hoc. 

`~strike prune [x]`
Current Action: N\A
Proposed Action: Remove any strikes >= x in "days old"
Scope: Leader\Captain, per alliance. Definitely not server-wide. 

Would be cool if it then listed the strikes that would be forgiven similar to how it works now with a thumbs up\down confirmation.

**Comment by tyejae** [comment]
I moved this over to the bot backlog, you can keep entering them here or hit us up in discord and we'll add them in the future.
