### ISSUE TITLE
Missing data from Campaign Node

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#23]
Heroes 2-4 is missing wave information

Screenshot:
![image](https://user-images.githubusercontent.com/11431194/48678086-74309300-eb33-11e8-904f-da116f410e8f.png)

Console:
![image](https://user-images.githubusercontent.com/11431194/48678092-827eaf00-eb33-11e8-90b4-0221f612814b.png)

**Comment by tyejae** [comment]
Fixed, will be live soon.
