### ISSUE TITLE
Captain Marvel Stats are decreasing from Levels 70-75

### ISSUE THREAD

**Issue by NobleDeen** [tyejae/msf.gg.public#230]
Captain Marvels main base stats (health, damage, armor) are decreasing in value between levels 70-75

**Comment by NobleDeen** [comment]
Update: It looks like multiple characters have decreasing stats from levels 70-75

**Comment by tyejae** [comment]
@NobleDeen Thanks for reporting. If you can remember which characters please list them. Will help expedite.

**Comment by tyejae** [comment]
@NobleDeen Nevermind, I found the bug. It was in the Base calculation. The total was correct. I have fixed it and it'll be live soon.

**Comment by NobleDeen** [comment]
Thanks for the response and update!
