### ISSUE TITLE
Last column on hero-total-stats is hidden behind scroll bar

### ISSUE THREAD

**Issue by bobby-game** [tyejae/msf.gg.public#231]
Horizontal Scroll Bar is missing or Page doesn't fit to Screen on 100% Zoom. 90% Zoom will give good results. Not working properly on Edge, Chrome or Firefox.
![image](https://user-images.githubusercontent.com/72401851/95099301-faf2b700-072f-11eb-8aa5-dd7b071f0d25.png)

**Comment by tyejae** [comment]
this is fixed, will be live soon. Look for the update message.
