### ISSUE TITLE
Strike Dates Invalid

### ISSUE THREAD

**Issue by tyejae** [tyejae/msf.gg.public#237]
The dates for the strikes are all showing invalid

**Comment by tyejae** [comment]
Seemed to be an issue with iOS. The date was valid. I just added a check for it. Will be live soon.

**Comment by ElCharismo** [comment]
As of 2021-01-25, this issue seems persistent. {Example Attached}

![Screen Shot 2021-01-25 at 11 06 00 AM](https://user-images.githubusercontent.com/6070959/105753391-7a81dd00-5efd-11eb-80fc-09a3a107d7fd.png)

**Comment by tyejae** [comment]
Thank you @ElCharismo, I'll reopen this

**Comment by tyejae** [comment]
Yay fixed.... is live now
