### ISSUE TITLE
Kingpin & Scarlet Witch shows Armor on Stats Grid

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#24]
From what I know, Kingpin and Scarlet Witch both have 0 armor no matter what, but the stats table is showing both with armor.

![image](https://user-images.githubusercontent.com/11431194/48803341-81ca5200-ecc6-11e8-900e-a72c81d576d0.png)

![image](https://user-images.githubusercontent.com/11431194/48803348-87c03300-ecc6-11e8-836a-eb9b41580c35.png)

![image](https://user-images.githubusercontent.com/11431194/48803354-8b53ba00-ecc6-11e8-92f8-c6bc2dc779f3.png)

**Comment by tyejae** [comment]
Fixed. Will be live soon.
