### ISSUE TITLE
Always Show Alliance Links

### ISSUE THREAD

**Issue by tyejae** [tyejae/msf.gg.public#262]
Could it be interesting to always keep that alliance bar even when you go to the different links, so you don't have to come back to the alliance page each time you want to switch from one link to another?

![image](https://user-images.githubusercontent.com/6165105/100616035-bb7ebc00-32d5-11eb-9e8a-740ae6ffccda.png)

**Comment by d90** [comment]
I'm d90 and I approve this improvement.

**Comment by tyejae** [comment]
Completely redid the alliance navigation.

![image](https://user-images.githubusercontent.com/6165105/106150686-cf5d6780-6138-11eb-9e99-1f71a44cdcc7.png)
