### ISSUE TITLE
Gear Search - Input freezes/lags during text input

### ISSUE THREAD

**Issue by SgtSQL** [tyejae/msf.gg.public#264]
I most frequently use Firefox mobile to search for gear pieces on MSF GG. it appears that you might have a fuzzy finder algorithm that is too greedy. After two or three characters of input, input will lag or freeze up. This also occurs while backspacing to clear the input field. Superior GT13 items is where I am currently experiencing the issue, as that is what I search for most.

**Comment by tyejae** [comment]
Likely can be improved upon. I believe is searches through all gear for every character. If I scope it down first, it'll save some process time. I couldn't get it to freeze up, but I did run a memory profile on the page and the scripting time was quite high.

**Comment by tyejae** [comment]
Is this still happening after the fixes I did?

**Comment by SgtSQL** [comment]
I honestly don't need to search in the text input field anymore now that it's alphabetical. There is still jank when typing in the search box.

I wouldn't prioritize it at all now that there's alphabetical sort, but if you used a library for the fuzzy finder, and and there is a millisecond constant for how often to send updates to the server, I would guess that that constant might need to be played with. Not sure if the request is being done asynchronously or synchronously. it seems like the UI thread is getting blocked.

But without alphabetical sort I don't care anymore. 😀👍

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
