### ISSUE TITLE
Superior Gear radio button cannot be selected

### ISSUE THREAD

**Issue by SgtSQL** [tyejae/msf.gg.public#265]
I may be misunderstanding how the gear filter is supposed to work. my expectation is that if I select the radio button for superior gear the radio button will show selected and I would see all superior gear items in the game. Instead The radio button only gets focus, it does not show selected, and always says no results found.
On the other hand when I click the basic gear radio button, the radio button gets focused and shows that it's selected and basic gear immediately shows up.
This occurs on Firefox mobile, chrome mobile, and in my PC browsers as well. I think the radio button input is bugged for superior gear, but maybe I don't understand how to use it as intended.

**Comment by tyejae** [comment]
I removed the superior gear option. It has been superceeded by the Tier13 option below
