### ISSUE TITLE
Alphabetical Gear Sort

### ISSUE THREAD

**Issue by SgtSQL** [tyejae/msf.gg.public#266]
I can't tell how the gear tier 13 results are currently grouped / sorted, but it is not alphabetical and it is not by character class e g bio tech mystic etc.
My most common scenario would be wanting to see them listed alphabetically by gear name. I could probably grab the JSON data and run it through a CSV converter to make my own spreadsheet, but I think alphabetical gear sort makes enough sense that it would be AN option even if not the default option.

**Comment by tyejae** [comment]
Agreed. I'd like to revamp the gear altogether honestly. I don't like how I implemented it from the start. Maybe this will encourage me to do so

**Comment by tyejae** [comment]
I fixed this to be alphabetical. Will be live shortly

**Comment by SgtSQL** [comment]
It's terrific. Thanks for the hard work.
