### ISSUE TITLE
Ascending/Descending Roster Sorting

### ISSUE THREAD

**Issue by GHosaPhat** [tyejae/msf.gg.public#268]
Could you please add an option to choose between ascending and descending order when sorting the roster?

Attached is a rough mock-up of a possible implementation.
![Sort Order Radio Buttons (Mock-Up)](https://user-images.githubusercontent.com/13453101/101082163-a3769900-3570-11eb-93cd-79d119c768f9.png)

**Comment by GHosaPhat** [comment]
One thing I didn't initially think of until I saw my own mock-up. This may require some additional logic to apply a "default" sort order. For example: when sorting alphabetically, the most common usage would probably be to have it sorted in **ascending** order, but when sorting by pretty much everything else (_power, level, star rank, etc._), it's most likely that users would want/expect it to default to sorting in **descending** order.

**Comment by tyejae** [comment]
This will be live soon!
![image](https://user-images.githubusercontent.com/6165105/101094220-47fcd900-3579-11eb-9521-e0eb25642d66.png)
