### ISSUE TITLE
Roster Sorting by Level - Zero <> NULL

### ISSUE THREAD

**Issue by GHosaPhat** [tyejae/msf.gg.public#269]
Could you please adjust the sort by Level option so that those with a level of zero (0) are not mixed in with the characters that haven't yet been unlocked (_see attached screenshot_)?
![Current Roster Sorting by Level](https://user-images.githubusercontent.com/13453101/101082471-1e3fb400-3571-11eb-89a4-a48dafa613e9.png)

I don't believe this would affect any of the other sorting options, but it might.

**Comment by tyejae** [comment]
It won't, and I fixed it now... it will be live in a little while

Example sorted alphabetically:
![image](https://user-images.githubusercontent.com/6165105/101091899-09b1ea80-3576-11eb-9abd-b6a3292da196.png)
