### ISSUE TITLE
Ultimus VI Raid, A5/I5: Alivepool - Incorrect wave data

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#27]
https://msf.gg/raids/raid_lvl_65/A5/raid_ult06_15
https://msf.gg/raids/raid_lvl_65/I5/raid_ult06_15

Site
![image](https://user-images.githubusercontent.com/11431194/49040231-d6624700-f176-11e8-9581-270fb7d2b9a3.png)

Actual
![image](https://user-images.githubusercontent.com/11431194/49040262-e67a2680-f176-11e8-9b29-a9862eccd572.png)

Video link: https://www.youtube.com/watch?v=bxcy5ZOGP2U

**Comment by tyejae** [comment]
Strange, that data is pulled straight from the files. I’ll look closer at that node. Thanks!

**Comment by tyejae** [comment]
Done
![image](https://user-images.githubusercontent.com/6165105/49199086-6361f780-f353-11e8-9f9a-7cd47556b96c.png)
