### ISSUE TITLE
Auto create well known community defined teams. 

### ISSUE THREAD

**Issue by d90** [tyejae/msf.gg.public#270]
I think it would be groovy if we could automatically create OR have a button that creates well known teams in the roster>teams section of the website. Click, generate all of them at once. Hey it could even be a bot command! The sky's the limit! 

~c command teams and any other teams that are being used regularly

BACON

**Comment by tyejae** [comment]
You got it!
![image](https://user-images.githubusercontent.com/6165105/101097275-22be9980-357e-11eb-8f65-78341f031951.png)
