### ISSUE TITLE
Display Current Shard Count (and Red Star Count) on Locked Characters

### ISSUE THREAD

**Issue by GHosaPhat** [tyejae/msf.gg.public#271]
It would be nice to display the current shard count (and red star count) for **locked** characters in a user's roster on MSF.gg like it does for **unlocked** characters. This, IMO, would provide users a way to see, at a glance, which characters they may be close to unlocking. Additionally, including the shard count as well as the (empty) red star count on locked characters would provide a better sense of visual continuity across the entire roster.

I know that the shard count of locked characters is included in the CSV uploaded by Zaratools RosterExtractor (_I'm not sure about what ToolBot provides_), although it sometimes gets "confused" in extracting the correct number of shards (_I'm fairly certain I haven't collected over 1,000 shards for Storm without unlocking her_). Since the red star count for locked characters is maintained, I'm sure this information is applied to the users' rosters somewhere that's simply not visible. If that's the case, I would assume that it should be "simply" a matter of duplicating the existing implementation used for unlocked characters. 

Of course, this suggestion would also basically necessitate implementing a method - either via bot, site, or both - to add/edit the current shard count for those users who want or need to do it manually, but that's a bit beyond the scope of this specific suggestion.

**Comment by tyejae** [comment]
This is done and will be live in a few hours
![image](https://user-images.githubusercontent.com/6165105/101187716-f5bbc680-3611-11eb-911f-da9abe2f1734.png)
