### ISSUE TITLE
Red Star Sorting Improvement

### ISSUE THREAD

**Issue by GHosaPhat** [tyejae/msf.gg.public#272]
I admit I was fairly confused the first time I tried to sort my roster on the site by red stars. It took me a good minute to understand what I was seeing:
![Current Red Star Sorting](https://user-images.githubusercontent.com/13453101/101126696-a0f05f80-35c1-11eb-880b-3fbfe09cbd90.png)

Once I understood that the locked characters that were "mixed in" with the unlocked characters because I've received a couple of "lucky" red star promotions here and there, it made a lot more sense. However, I thought of three possible ways to avoid confusion in the future. These ideas could be combined in different ways to, perhaps, offer an even better view of this particular information:

1) Keep all the locked characters at the bottom of the roster regardless of red star count. When this sorting method is chosen, the locked characters could then be sorted according to _their_ red star count.
2) Sort only by _filled_ red stars (where star rank meets or exceeds red star count).
3) Display the red star count on locked characters.

If option 3 is implemented, please refer to issue #271  for some additional suggestions regarding the display of red star (and character shard) information on locked characters.

**Comment by tyejae** [comment]
Adding filled red stars option
![image](https://user-images.githubusercontent.com/6165105/101189152-e50c5000-3613-11eb-94cd-1a8736684885.png)
