### ISSUE TITLE
Characters and roster missing

### ISSUE THREAD

**Issue by benglish5** [tyejae/msf.gg.public#274]
Not sure if you are just doing maintenance, but my roster and available characters are not showing at all currently.  War defenses for our alliance are still showing correctly though.  Screenshot is attached of what is visible.
![Screenshot_2020-12-07 Characters MARVEL Strike Force Database MSF gg(1)](https://user-images.githubusercontent.com/75633953/101383407-1771b380-3887-11eb-988e-1092f7689e47.png)
![Screenshot_2020-12-07 Characters MARVEL Strike Force Database MSF gg](https://user-images.githubusercontent.com/75633953/101383409-180a4a00-3887-11eb-8790-96c9ff813039.png)

**Comment by tyejae** [comment]
Thanks for reporting. This issue was unique to Firefox (I'm assuming that is what you were using). I just published the fix for this. Please test it out.
