### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by jaumard** [tyejae/msf.gg.public#275]
Hello,

I'm a mobile developper and would like to do msf.gg in a mobile app to make mobile access more usable and fun.

Let me know what you think of it :) would love to work on that.

Cheers

**Comment by jaumard** [comment]
One idea out of my mind would be to be able to check screenshots from the roster in app, like this no need to have a server to analyze the roster image. So less cost for you.

**Comment by tyejae** [comment]
Do you have Discord? Let's chat. If you do DM TyeJae#2513

**Comment by jaumard** [comment]
Sure, mine is Jaumard#8500, I sent you a DM
