### ISSUE TITLE
"By Level" auto re-sort after updating character forgets 0 <> NULL

### ISSUE THREAD

**Issue by GHosaPhat** [tyejae/msf.gg.public#280]
The sort by level option initially works properly separating the level zero (unlocked) from the NULL (locked) characters. However, if I update one of the level zero characters to another value, the list re-sorts itself (as expected). However, after the re-sort, the zeroes and NULLs become mixed together. It's a minor frustration that only affects when I'm filling in missing level values after uploading my roster data from the Zaratools **Roster Extractor** utility, but it makes that update process take longer than it should.

**Comment by GHosaPhat** [comment]
Just for reference, here are a couple of screenshots after my most recent update from **Roster Extractor**. Note the character immediately to the right of Hand Sentry (circled) in each.
![Before updating Crossbones](https://user-images.githubusercontent.com/13453101/102660362-829d6e80-4140-11eb-9750-f72997adba1f.png)

![After updating Crossbones](https://user-images.githubusercontent.com/13453101/102660374-8cbf6d00-4140-11eb-871f-d16d7b6dbd46.png)

**Comment by tyejae** [comment]
I could not recreate this issue. I believe the issue may have been fixed already. Also MANTIS now sends level 0 instead of null
