### ISSUE TITLE
Hydra Grenadier Damage Calculation 

### ISSUE THREAD

**Issue by mcantrell** [tyejae/msf.gg.public#283]
It looks like there's a significant difference for grenadier's damage when compared to the game's value:

![image](https://user-images.githubusercontent.com/20870/103444368-5e0bc100-4c2d-11eb-95a7-1603097ba80c.png)
![image](https://user-images.githubusercontent.com/20870/103444387-7e3b8000-4c2d-11eb-9e65-87e55fc1cd7a.png)
![image](https://user-images.githubusercontent.com/20870/103444397-8a274200-4c2d-11eb-914f-2674eeec63d0.png)

**Comment by tyejae** [comment]
This will be OBE with the API
