### ISSUE TITLE
Alliance Image Doesn't Match Selected

### ISSUE THREAD

**Issue by GHosaPhat** [tyejae/msf.gg.public#284]
This is a minor annoyance, but the alliance image on the **MY ALLIANCE** page doesn't match what is selected in the **EDIT ALLIANCE** dialog. It _does_ show correctly in the **Player Profile** section of the **MY CHARACTERS** page. Please refer to the attached screenshots:
![Alliance Image - Edit Alliance - Selected](https://user-images.githubusercontent.com/13453101/103660721-8d734400-4f33-11eb-898f-7ca9db8560a3.png)
![Alliance Image - Player Profile - Correct](https://user-images.githubusercontent.com/13453101/103660793-a3810480-4f33-11eb-8ff5-4ea2d88604fe.png)
![Alliance Image - My Alliance - Incorrect](https://user-images.githubusercontent.com/13453101/103661053-e80ca000-4f33-11eb-8a80-e9f444efb972.png)

**Comment by tyejae** [comment]
Fixed, will be live in a few hrs. Thanks for reporting
