### ISSUE TITLE
Leader changed No recourse to manage the alliance in msf.gg

### ISSUE THREAD

**Issue by Rotorheads** [tyejae/msf.gg.public#287]
Need a provision to have more than one leader or the ability to remove a vacated leader.

**Comment by tyejae** [comment]
Vacated leaders I've always done manually. How would you propose removing a vacated leader?

**Comment by Rotorheads** [comment]
It is not so much removing a vacated leader. It is having the ability to have redundant controls. Having a second “leader” that has the ability would be most effective. As it stands right now, as in my alliance in gg, the leader is not capable of logging in (forgot creds). Therefore the alliance is locked up. This is because there is only one leader allowable.

BTW the leader has messaged you several times to see about resolving the issue.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tyejae** [comment]
If he's messaging me through the email it's likely I'll never see it. The email that sends out the password resets is automated and is not monitored. Have him reach out to me on Discord and I can help him. 

My apologies for any delays, I do this for free on my spare time as a courtesy for the community. And there's only one of me
