### ISSUE TITLE
Suggestion: Enemy inspector should scroll with page

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#29]
When you've scrolled down the page to see additional waves, the enemy inspector stays at the top of the page.

![image](https://user-images.githubusercontent.com/11431194/49128562-ccc50600-f280-11e8-9276-5fecc47c5b60.png)

**Comment by tyejae** [comment]
I’ve thought about doing this so many times. Guess it’s time to do it

**Comment by tyejae** [comment]
When you click on an enemy it moves the enemy inspector into view.
Here is an image where it's at the bottom of the page. 
![image](https://user-images.githubusercontent.com/6165105/49198511-aa9ab900-f350-11e8-8eb7-0c089dc47c5f.png)
