### ISSUE TITLE
not sure if its me, adding counters

### ISSUE THREAD

**Issue by 50gnr** [tyejae/msf.gg.public#294]
added a merc km counter
everything looks good
does not show up in our counter list in discord?
does it take time to move over or did i do something wrong?

Ragnarök - delta

**Comment by tyejae** [comment]
Hey @50gnr, you likely have the option for counter commands turned off in the bot. Head on over to our Discord (https://discord.gg/u9pYqpJ) and myself or one of my moderators can help you debug why your custom counters aren't showing up.

**Comment by 50gnr** [comment]
Ya 100% was me, dug deeper and got leader to activate it!

Thx for your time tyejae, fantastic product!
