### ISSUE TITLE
Consider adding more gear tier material information

### ISSUE THREAD

**Issue by tyejae** [tyejae/msf.gg.public#3]
For example:
- 2x Improved Classified Files
  - Needs 2x Improved Secret Intel
- 4x Improved Skill Focus Catalyst
  - Needs 2x Improved Focus Catalyst Part
  - Needs 2x Improved Basic Catalyst
- 1x Improved Endurance Program

Because Improved Immunity Regimen also needs: 
- 2x Improved Classified Files
- 1x Improved Endurance Program

The total needed materials are: 
- 8x Improved Secret Intel **Common material**
- 8x Improved Focus Catalyst Part
- 8x Improved Health Catalyst Part
- 16x Improved Basic Catalyst **Common material**
- 2x Improved Endurance Program **Common material**

**Comment by AlbertoMonteiro** [comment]
Done!! Very very very very nice!!!!!!!

![image](https://user-images.githubusercontent.com/836496/41154720-771f8c32-6af1-11e8-8190-ace27d9501c2.png)
