### ISSUE TITLE
MSF.gg site: Difficulty Dropdown Box for Greek Raids

### ISSUE THREAD

**Issue by d90** [tyejae/msf.gg.public#308]
Make the dropdown box for greek raids like it's displayed on the site for Ultimus raids.

**Comment by tyejae** [comment]
Hey @d90 can you explain what you mean here?

**Comment by tyejae** [comment]
@TyeJae per your comment on GitHub: the difficulty message for all the Greek raids on the website are missing the drop-down box that exists for ultimus
![image](https://user-images.githubusercontent.com/6165105/110780633-23706700-8222-11eb-899c-b1d50e0ca575.png)

![image](https://user-images.githubusercontent.com/6165105/110780675-2ec39280-8222-11eb-9b07-549819e962e5.png)

**Comment by tyejae** [comment]
Done will be live when I update next
