### ISSUE TITLE
Suggestion: Better view for T4 ability

### ISSUE THREAD

**Issue by Syhnd** [tyejae/msf.gg.public#311]
Hi,
I really like the new meta page and seeing what the T4 really do is one of the most important thing why we go to msf.gg. 
Can there be a way to better see what the T4 does on the character page rather than going back and forth from 7 to 6 (or 5 to 4 for passive) on this page?

**Comment by tyejae** [comment]
It does this now. If you hover (or tap for mobile) on the ability icon, it shows you.
![image](https://user-images.githubusercontent.com/6165105/110707342-64329680-81b6-11eb-9c30-3b92471a4b51.png)
