### ISSUE TITLE
Suggestion: Group META page (T4/iso) by team

### ISSUE THREAD

**Issue by Syhnd** [tyejae/msf.gg.public#312]
On the site, META page, that would be great if we could have a way to group characters by team.
Such as with the bot when we request ~t4 -t sym or ~iso -t sym

**Comment by tyejae** [comment]
Done will be live the next time I update the site. Thanks for the suggestion!
![image](https://user-images.githubusercontent.com/6165105/110713544-57667080-81bf-11eb-96f4-27a3147f252a.png)
