### ISSUE TITLE
Suggestion: Better iso META page

### ISSUE THREAD

**Issue by Syhnd** [tyejae/msf.gg.public#313]
On the META page, iso section, I think that it might be useful to have a little hint to see :
- what the iso bonus attack does for striker, 
- the crit chance and crit damage for raider, 
- focus for skirmisher
- health for healer and fortifier (since the barrier is % of health)

**Comment by tyejae** [comment]
If you hover (or tap on mobile) on the iso image, it already gives you all this data.
![image](https://user-images.githubusercontent.com/6165105/110707256-46653180-81b6-11eb-95e1-cc307914d3ee.png)

**Comment by Syhnd** [comment]
I was talking about the concrete benefit for that specific player 

For example for ghost :
- striker lv5 : on iso bonus attack : Attack primary target for 210% damage + 17% Piercing damage. Change Speed Bar by -25%.
               Health : 230317 + 20% (unlocked at tier 4 bonus) + 10% iso-8 health bonus = 269800
- raider lv5 : crit chance 10% + 25% iso tear 5 bonus = 35% chance
               Health : 230317 + 20% (unlocked at tier 4 bonus) + 10% iso-8 health bonus = 269800
- and so on...
