### ISSUE TITLE
iso confidence keyword ironheart

### ISSUE THREAD

**Issue by cptngorgutz** [tyejae/msf.gg.public#314]
When searching for iron heart, she wont display without ironheart  being all one word.
![image](https://user-images.githubusercontent.com/52824119/107981866-dd293e80-6fba-11eb-87ac-6bc275faf78c.png)
![image](https://user-images.githubusercontent.com/52824119/107981890-eadec400-6fba-11eb-80ae-de66772a1cb7.png)

**Comment by tyejae** [comment]
Her name is Ironheart, not Iron Heart. So this is correct. The inverse of that would be searching for Black Panther by typing Blackpanther.
