### ISSUE TITLE
QoL Update Request - Add Room Names to War Defense page

### ISSUE THREAD

**Issue by GHosaPhat** [tyejae/msf.gg.public#317]
On the **WAR DEFENSE** page, it would be nice to see the rooms to which each member is assigned so you don't have to switch back to the **WAR LAYOUT PLANNER** page for that information. Something like this:
![mock-up](https://user-images.githubusercontent.com/13453101/109097210-84595480-76e4-11eb-91c5-1ff02351e630.png)

**Comment by tyejae** [comment]
Will be live the next time the site updates
![image](https://user-images.githubusercontent.com/6165105/110706802-a4454980-81b5-11eb-91d8-c7cc8a9d7524.png)
