### ISSUE TITLE
Suggestion: META info on character page

### ISSUE THREAD

**Issue by Syhnd** [tyejae/msf.gg.public#319]
Hi, 
It could be very useful to have the iso and T4 data that are in the META section directly in the character page

That way all the data is centralized in the same place and it's way more user-friendly

Best regards

**Comment by tyejae** [comment]
Abilities done
![image](https://user-images.githubusercontent.com/6165105/110192932-41873300-7dee-11eb-8044-ac4c6a46d02e.png)

**Comment by tyejae** [comment]
And ISO already did it. Will be live at the next update.
![image](https://user-images.githubusercontent.com/6165105/110192957-67143c80-7dee-11eb-8f97-a7fc1c5cbc65.png)

**Comment by Syhnd** [comment]
You're a boss! :)
