### ISSUE TITLE
Export war defence to .csv.

### ISSUE THREAD

**Issue by Magakahn** [tyejae/msf.gg.public#322]
Could it be possible to look at a way to export from war defence to .csv? 
Might be a feature in the allready existing personal/alliance/cluster roster download say with a column for war defence that lists numbers between 0 and 8. 0 = not used in war defence. 1 = used in war defence team 1 etc. Or Just a column for "used in defence?" True/false. 

With this we can do an easy rewiev of everyones defence at the same time as we have their entire rooster avaliable. Way easier than looking at one room at a time inngame.

**Comment by tyejae** [comment]
Done will be live next update. Thank you for the suggestion!

![image](https://user-images.githubusercontent.com/6165105/110183765-d37e4400-7dcc-11eb-945f-5ad0df585198.png)

**Comment by Magakahn** [comment]
U are awsome!

lør. 6. mar. 2021, 00:07 skrev tyejae <notifications@github.com>:
