### ISSUE TITLE
Highlight nodes that match the currently hovered node

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#324]
In some raids, the same node is present in multiple locations. It would be nice if the same nodes in the raid would highlight as well to understand how the raid is laid out better. I believe the names for similar nodes are the same if there is no internal id that matches them together

e.g.
![image](https://user-images.githubusercontent.com/11431194/110169791-0e24b400-7dae-11eb-866a-16a9cd60f485.png)

**Comment by tyejae** [comment]
Done! Will be live next publish
