### ISSUE TITLE
DD4 Node 15 Wrong Descriptions

### ISSUE THREAD

**Issue by ByAnIrishman** [tyejae/msf.gg.public#325]
The descriptions for the waves in DD4 node 15 are off. They are showing the description for the wave after rather than the wave itself.

**Comment by tyejae** [comment]
Can you explain more? I'm currently on DD4 Mission 7 and the characters its saying are in wave 1, are the characters that dropped.

**Comment by ByAnIrishman** [comment]
Yeah no problem. Its specifically on node 15, the final node, where there are discrepancies. For example, it says the taskmaster will do his special and ultimate under wave 1 but there isn't a task master in wave 1. He doesnt show up until wave 2. It does this throughout with the description being a wave off

**Comment by tyejae** [comment]
Thank you for the specifics. I'll check on this one.

**Comment by tyejae** [comment]
This has been fixed for a while now. Forgot to close this issue.
![image](https://user-images.githubusercontent.com/6165105/165604856-659f3a52-f5db-416f-ab5c-3fa77a8491ff.png)
