### ISSUE TITLE
Moving/coying team into main folder saves an "undefined" folder name instead of team name

### ISSUE THREAD

**Issue by geekahedron** [tyejae/msf.gg.public#328]
When moving or copying one or more teams into the "Main" folder, the `~t` command shows "undefined" in the folder list instead of the team(s) that were copied.

The teams can be moved or copied into a different folder and then function normally.

New teams created in the Main folder behave properly.

[Discussion](https://discord.com/channels/455443542358360064/698036394601218098/818848954020134933)
> THE RockToday at 9:13 AM
> Can you help me fix my link between discord and the msf.gg site... I'm not able to get the BOT to display my teams, but it does display my roster.
> I just tried it here, and it does the same thing.
> The sequence that got me to this point was I moved the teams out of a folder using the "Move to Main" button, then deleted the folder.
> It appears to be related to the fact that I moved the teams from the deleted folder then deleted the folder. I just created a new team in that folder, and it shows up fine.

**Comment by tyejae** [comment]
Thank you for pointing this out! I've been seeing undefined names and didn't knwo where they were coming from. This makes sense now!

**Comment by tyejae** [comment]
Fixed! Will be live the next time I update the site
