### ISSUE TITLE
Changelog hasn't been updated in a while

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#34]
This changelog: https://msf.gg/changelog

I know most changes are written out to the discord channel, (trying to avoid that), would be nice if the notes were duplicated to the website

**Comment by tyejae** [comment]
There's nothing I like seeing more than a change request from chronolinq! Thanks for keeping me honest. I'll be getting to all of these.

**Comment by tyejae** [comment]
Just finished committing this. Added 46 updates to the changelog.
