### ISSUE TITLE
Red stars not clamping to yellow star count for stat calculation

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#342]
At 2/5 stars:
![image](https://user-images.githubusercontent.com/11431194/111881875-da31bd00-896f-11eb-93d8-4cf855c84ab6.png)

At 2/2 stars:
![image](https://user-images.githubusercontent.com/11431194/111881888-e61d7f00-896f-11eb-8772-54af182d465f.png)

Bonus loading my character:
![image](https://user-images.githubusercontent.com/11431194/111881862-c8e8b080-896f-11eb-9dce-4efb9f7ac829.png)

**Comment by tyejae** [comment]
This will now take the Math.min(red, yellow) for stats
