### ISSUE TITLE
Iso T4 Confidence Filter not opening

### ISSUE THREAD

**Issue by chris-ware** [tyejae/msf.gg.public#344]
The filters selected dropdown doesn't seem to open. I've tried it in the latest versions of Vivaldi, Chrome and Firefox to the same result.

**Comment by tyejae** [comment]
Is this Mobile or Desktop?--
TyeJae

**Comment by chris-ware** [comment]
Desktop. Happy to provide screenshots and console logs if helpful.

**Comment by tyejae** [comment]
Done, will be live in the next hour
