### ISSUE TITLE
Suggestion: Remove alert "Drag and drop teams to change order"

### ISSUE THREAD

**Issue by chuntsen** [tyejae/msf.gg.public#348]
Hi, when using the MSF.GG site, each time I load the 'My Teams' page, or any of the folders within 'My Teams', the alert "Drag and drop teams to change order (saves automatically)" appears. Even after clicking the cross, it still appears the next page.

Suggest to have it appear once, then maybe have a cookie to remove it for the next time.
![msfgg2](https://user-images.githubusercontent.com/81957615/113557058-fe5bf200-962f-11eb-9f6b-60c7f866b53a.png)
![msfgg1](https://user-images.githubusercontent.com/81957615/113557062-0025b580-9630-11eb-9a6a-69c3f58d296b.png)

**Comment by tyejae** [comment]
Done, will be live later today. Hides the notification for 1 week.
