### ISSUE TITLE
Maps QoL

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#35]
1. Spinner on the Download Maps button would be good since it takes a bit of time. Not sure if it's running or not
2. Download Button should also be disabled when clicked to prevent multiple downloads until it is finished processing
3. The trait tags on nodes covers the top bar 
![image](https://user-images.githubusercontent.com/11431194/51862687-fc7da200-22f3-11e9-8384-1ed34adf3bc5.png)
4. Raid paths that meet without a node could be cleaned up
![image](https://user-images.githubusercontent.com/11431194/51862782-364ea880-22f4-11e9-803b-da18927a7fd7.png)

On the downloaded map:
5. Not sure if the trait font can be included but it would look a lot better than what's currently there imo
6. The background color changed to match the site would help with readability

**Comment by tyejae** [comment]
1. Working this - trying to see if I can get a callback from the method I'm using to generate it
2. Another good idea, will rely on the callback method from #1
3. Easy fix, will do this soon
4. Done, this is live now. I actually fixed this already and updated the datamine and it screwed it up again.
5. Not sure I can supply the utility a font to use. I will see if I can, or see if there is an alternative utility
6. This should be feasible.
