### ISSUE TITLE
Suggestion: See what the upgrade value from T3 to T4 does

### ISSUE THREAD

**Issue by Syhnd** [tyejae/msf.gg.public#352]
Hi,
This is a follow up for suggestion #311 

On META and character page, what would be nice is by default, seeing 6/6/6/4 abilities since T4 are the most common bottleneck
Then under each one, seeing what is the change gained with T4, for example with Ghost 
Basic lv6 : Attack primary target for 250% damage + reduce Speed Bar by 25%.
--Change at lv7: Attack primary target for +25% damage
------------------Assist/Counter info: Attack primary target for +35% damage and +2% Piercing damage
--T4 Confidence 6.8% (2725 USERS)

This way we easily see the real value of the T4 upgrade, rather than seeing the value of the overall ability

**Comment by tyejae** [comment]
Ahh thanks for putting this in! I just was coming here to put this after our conversation on Discord.

**Comment by Syhnd** [comment]
Done in #391 :)
