### ISSUE TITLE
Suggestion: add a legendary "calculator"

### ISSUE THREAD

**Issue by Syhnd** [tyejae/msf.gg.public#356]
Hi,

When I was still a beginner/mid game I made a tool to keep track of my progression and calculate my farming needs for legendary events.

You can check the link here : https://docs.google.com/spreadsheets/d/1hFbH_v53wyv1k954dzfX7OLJFCHvEYWlN8Dw8QApwpM/edit#gid=703659753

The only downside is that I have to enter my shard progression manually.

Can there be a legendary "farming calculator" tool in the site?

Best regards

**Comment by TheBhim** [comment]
Strongly second this, I use a infographic and edit it with paint.^^ That is even worse.^^ Viewing the progress via a dedicated page, calculating in your actual roster would be great. Also very helpful in reminding you to farm shards for toons ahead of the next legendary cycle, something I often forget to do.

**Comment by Syhnd** [comment]
> Strongly second this, I use a infographic and edit it with paint.^^ That is even worse.^^ Viewing the progress via a dedicated page, calculating in your actual roster would be great. Also very helpful in reminding you to farm shards for toons ahead of the next legendary cycle, something I often forget to do.

By the way, since last post I've updated my spreadsheet to make it possible to import from msf.gg or from MANTIS, check it out :)
https://docs.google.com/spreadsheets/d/1hFbH_v53wyv1k954dzfX7OLJFCHvEYWlN8Dw8QApwpM/edit#gid=1443061190

**Comment by waellerbe** [comment]
@Syhnd  Your spreadsheet solution is **amazing**. As time allows. I will view your spreadsheet on my laptop. Thank you for sharing the current version here on GitHub.

**Comment by waellerbe** [comment]
> 

@TheBhim  I am **no** expert on the matter, I understand that JavaScript can help to extract information from image files. MSF.gg has a genius process that will extract information from roster screenshots. Incredible ingenuity for sure.

**Comment by Syhnd** [comment]
I guess it can be closed now :) great job!
Suggesting enhancements in new thread.

**Comment by jetroh** [comment]
This has been implemented.
