### ISSUE TITLE
Bot Counter Graphic - Colorblind Friendly display

### ISSUE THREAD

**Issue by BazInTheAZ** [tyejae/msf.gg.public#361]
As a colorblind (protanopia) person, it's difficult to determine target priority in the generated counter graphic. As there are other types of colorblindness, changing the colors may be insufficient. I would suggest a number badge, in addition to color, to indicate priority. (See attachment)

![counter-MERC-sample](https://user-images.githubusercontent.com/453526/116320197-a450d700-a76c-11eb-96ea-542d3303e0ef.png)

**Comment by tyejae** [comment]
Which do you prefer?

![image](https://user-images.githubusercontent.com/6165105/116758782-b1b4ce00-a9c5-11eb-80cd-6dd83996064c.png)
![image](https://user-images.githubusercontent.com/6165105/116758795-b9747280-a9c5-11eb-8f72-599c0a3219ee.png)

**Comment by tyejae** [comment]
I think the white background with black text pops out more

**Comment by BazInTheAZ** [comment]
> I think the white background with black text pops out more

I would agree with that.

**Comment by tyejae** [comment]
Perfect we will go with that. I'm going to have a colorblind option that will allow people to turn this on.

**Comment by BazInTheAZ** [comment]
Thanks, @tyejae! I appreciate you.

**Comment by tyejae** [comment]
This is done. Will be live in the next few days. If you have any other colorblind options, please let us know.
