### ISSUE TITLE
Stats not updating in MSF bot

### ISSUE THREAD

**Issue by wvangosen1** [tyejae/msf.gg.public#362]
I set up the MSF.gg bot with a different account before I realized it wasn't syncing.  I then set up the correct account and email to sync, but didn't want to manually enter everything i did in the previous account.  So, I exported my roster from one account and imported into the synched account.  Everything is there and seems to calculate correctly, but when I type ~r stats it only shows the STP and no other stats.

![MSF](https://user-images.githubusercontent.com/83456281/116695757-05f08b80-a98f-11eb-9970-71f580add821.png)

**Comment by tyejae** [comment]
The status update every day at 8am PST and 10am PST. If you look at the bottom of the embed it shows you how much time is left til it updates or when it last updated
