### ISSUE TITLE
Flash Events listed under "Other Events" instead of "Flash Events"

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#365]
Both of these can be under Flash Events

![image](https://user-images.githubusercontent.com/11431194/116962250-551e1100-ac5a-11eb-9f2f-1fc58ddcb7d1.png)

**Comment by tyejae** [comment]
![image](https://user-images.githubusercontent.com/6165105/165598123-25742e41-c4ae-4191-88c9-c7cefa08ad6b.png)
