### ISSUE TITLE
REVISED -> Spreadsheet ID -> Captains / Leaders ID is brought into members ID

### ISSUE THREAD

**Issue by burtcasey** [tyejae/msf.gg.public#370]
On the webpage,  I'm managing some members rosters on their behalf.  By default when I open another members roster, and select the MSF Tools button,  my spreadsheet ID was replaced into the members spreadsheet id.  

So two Related issues:
1) It shouldn't be updated with the Captains/Leaders ID
2) Once roster is updated incorrectly, it's very difficult to clean up.  You can't clear out the entire roster or individual toons easily.   (Another reason I've seen these updated incorrectly is user error when they have multiple msf.gg/discord/toolbot accounts, and link incorrectly). If there's an easy way to clear the roster, please let me know.  Thanks. 

Also: I was treating this as lower priority with the hope that user data api would be coming soon,  I understand that's probably not the case so this is higher priority for me.  

**Additional Whining:**
For the member this happened to,  I'm a 12 mil TCP member with full roster,  he had 50 toons.  I had to manually clear his roster.  Then he subsequently updated his roster via toolbox,  went in via the maf.gg bot and updated it,  and it of course, re-loaded my roster.  I mistakenly kept my id in as proof of the issue.

**Comment by burtcasey** [comment]
I noticed issue 1 is a duplicate of  #350,  sorry about that.

Issue 2, I don't see as a duplicate.

**Comment by tyejae** [comment]
MSF Tools ID no longer shows up when updating someone else's roster
Also added a delete button to the character edit popup
![image](https://user-images.githubusercontent.com/6165105/165601535-51ee95ea-ee58-4728-819c-60c52391cec0.png)


Will be live sometime today
