### ISSUE TITLE
Dim or hide gear you have enough of in DD Planner

### ISSUE THREAD

**Issue by Brettflan** [tyejae/msf.gg.public#377]
An option to dim or completely hide the gear you have enough of in the DD planner would be nice; I went ahead and added dimming for them myself using Tampermonkey to add this CSS:
`.fade-in.has-enough-inventory div, .fade-in.has-enough-inventory img { opacity: 0.4; }`
Which results in:
![image](https://user-images.githubusercontent.com/592130/130366958-55bf9e09-a362-407f-9ff0-7d188e8afb0d.png)

It would be nicer to have a toggleable option on the page for it or something like that though, and in that case it would probably be nicer to just have it hide them completely when toggled on rather than just dimming them.
If the toggleable option is more trouble than it's worth, just the dimming CSS would be nice to make it more visually obvious which gear you're not currently in need of rather than hiding them completely.

**Comment by tyejae** [comment]
Will be live shortly
![image](https://user-images.githubusercontent.com/6165105/135739192-fa3e91d0-a727-42fe-8b10-48897f59ebe7.png)
