### ISSUE TITLE
Suggestion: Ability to add gear inventory count in DD planner

### ISSUE THREAD

**Issue by mark-casias** [tyejae/msf.gg.public#378]
Since it is a bit cumbersome to switch to the inventory tab and then back to the DD planner, I suggest the ability to click on an item, have either a pop-up or just add an input field, and enter the inventory directly.

**Comment by tyejae** [comment]
Coming soon, you will be able to click on the item and update the quantity
![image](https://user-images.githubusercontent.com/6165105/135738469-c769a6ba-d4ae-46be-aba2-27cc323cd5c4.png)
