### ISSUE TITLE
Error editing War teams - Two teams are unable to be edited or changed

### ISSUE THREAD

**Issue by measmyself5** [tyejae/msf.gg.public#379]
In war defense my team 10 is not letting me edit anything  always showing the attached error.
![Screenshot 2021-09-30 064812](https://user-images.githubusercontent.com/91678584/135468319-f5b9b870-698d-4bc8-831c-0935cdd107c0.png)

This is what i tried.

Refreshing screen
clicking on where the profile would be to maybe unassigned an invisible char.  (resulted in error)
clear cashe and cookies 
logged out and back in again.

**Comment by measmyself5** [comment]
5f18b58e71386 -> user ID if that helps.

**Comment by measmyself5** [comment]
IN addition.  My team 9, although filled is having the exact same error.  not letting me assign, or unassigned .  so team 10 and team 9 are both having issues

**Comment by tyejae** [comment]
Figured this one out, will be live later today. If you are in the Discord server, look in #site-changelog
