### ISSUE TITLE
Alpha Maps not complete

### ISSUE THREAD

**Issue by jmrados** [tyejae/msf.gg.public#38]
It looks like the Alpha Maps might not be complete when viewing older maps compared to the one on the site. 
![image](https://user-images.githubusercontent.com/13193072/52390863-3ec78180-2a60-11e9-86a2-1a54222a12c8.png)

https://i.imgur.com/JsXQo8V.jpg

**Comment by tyejae** [comment]
It is complete, looks like there is just an extra line. I’ll fix this soon.

**Comment by tyejae** [comment]
Done, live now.
