### ISSUE TITLE
Add Upgrade Text To Character Abilities

### ISSUE THREAD

**Issue by tyejae** [tyejae/msf.gg.public#391]
Yeti — Today at 11:58 AM
On the msf.gg website, would it be possible to hit a toggle to highlight the changes from nonT4, to the T4 enabled? I constantly cycle between these to see what the msf.gg code interprets the difference is, because often times the in-game T4 field is truncated.

**Comment by tyejae** [comment]
This has been completed
![image](https://user-images.githubusercontent.com/6165105/145852278-3d0ce9a4-0b08-4a2d-80f8-f599533b0ec4.png)

**Comment by Syhnd** [comment]
This is basically my #352 request, thanks :)
