### ISSUE TITLE
Global should be listed under Origin, not Flavor

### ISSUE THREAD

**Issue by tyejae** [tyejae/msf.gg.public#4]

**Comment by TheBooGhost** [comment]
Agreed, it's been bugging me for ages. :)

**Comment by tyejae** [comment]
Done

![image](https://user-images.githubusercontent.com/6165105/41488669-0a6923f8-70a2-11e8-9424-e1dc524c8ae6.png)

**Comment by tyejae** [comment]
This will be out with the next patch to the site
