### ISSUE TITLE
Ability to disable passives on stat table

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#402]
This feature would show stats on the character stat table without passive stat bonuses. While some characters like Omega Red will never be without his passive health increase, it is useful for comparison purposes to disable his health bonus to determine which character on Weapon X has the actual highest health in a battle (since Omega Red's health passive applies to the whole team). This feature would be especially powerful when coupled with the "My Roster Stats" table.

The UX could be changing the passive to "0" or an additional checkbox (that is checked by default)

**Comment by tyejae** [comment]
This is done, will be live later today
![image](https://user-images.githubusercontent.com/6165105/149008595-2ff558aa-02f0-406a-b4ef-945fc7d51497.png)
