### ISSUE TITLE
History of upgrades on character look right, but whats shown is sometimes less

### ISSUE THREAD

**Issue by mscolaro1** [tyejae/msf.gg.public#411]
My total roster power is off more than a million, and I can find numerous characters that display wrong

![image](https://user-images.githubusercontent.com/18217894/149363956-b3e868ab-ad37-4654-856a-3e0c9c4f6665.png)

![image](https://user-images.githubusercontent.com/18217894/149364003-ad43e02b-b514-4464-95a5-90c1111befbe.png)

**Comment by tyejae** [comment]
Your most recent update does not show in the history. The history is what has happened. So looks like your most recent read (using ToolBot?) did not read those characters correctly. Go to your ToolBot sheet and see what it says for those two characters.

**Comment by tyejae** [comment]
I just looked at your sheet. Look here, your Red Skull is reading 52007 from ToolBot.

![image](https://user-images.githubusercontent.com/6165105/149373475-96815116-890d-4367-9902-0cb428a4e9dc.png)

**Comment by mscolaro1** [comment]
I didn't mention if it matters, that I use Mantis.  Not any of the screenshot tools.

**Comment by mscolaro1** [comment]
![image](https://user-images.githubusercontent.com/18217894/149378269-466aacf9-17ba-45c9-898b-81e4434f617a.png)

**Comment by mscolaro1** [comment]
Last time I used ToolBot was 12/20/2020.  How do I make whatever your using from it, go away?

**Comment by tyejae** [comment]
Did you run the `~ur toolbot` command? Because if you did, don't. :D
You'll have to delete your MANTIS character folder and then reupload. It will fix everything. I'm not sure where that is at though. Are you on the MANTIS discord channel? If so, pop a question in there to ask where to delete this.

**Comment by mscolaro1** [comment]
Hurrah, it was fixed by deleting one .json file and re-running the scanner.  Thank you.
