### ISSUE TITLE
Unable to save Teams

### ISSUE THREAD

**Issue by LrdRoone** [tyejae/msf.gg.public#42]
I have made an account, logged in and made a team. 

Repro Steps:
1. Be logged in
2. Go to Characters Screen and select Build Team
3. Select 5 characters (DD/IF/LC/JJ/Pun)
4. Hit Go
5. Select Save Team
6. Enter Team name (Defenders)
7. Hit Done

Actual Result: Get a screen that says "You don't have any teams! To create a team, go to Characters and Press Build Team"

Expected Result: Team that was created is displayed here.

I have tried on multiple browsers, multiple computers with same result

**Comment by tyejae** [comment]
Fixed this today

**Comment by WushuMonk** [comment]
I am having the exact same issue. For several days now. Using Chrome and Edge browsers.
