### ISSUE TITLE
MSF.gg DNS does not resolve in Europe

### ISSUE THREAD

**Issue by geoox** [tyejae/msf.gg.public#421]
MSF.gg DNS does not resolve in Europe.

There's probably a faulty DNS policy for geolocation as if I'm using a VPN to connect to US servers, the DNS resolves correctly whereas from Europe there is the following error:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/24357659/153882703-3073a7d7-e9c8-425a-9822-89b7cb54b8ba.png">

**Comment by geoox** [comment]
The problem is now solved. I will close the ticket, however more support/transparency on the issues would be awesome

**Comment by tyejae** [comment]
@geoox We transferred our site to a new provider and the previous host did not properly handle DNSSEC which messed everything up. Finally had to have the new provider contact the previous provider to tell them they messed up.
