### ISSUE TITLE
DD Planner not updating gear quantities

### ISSUE THREAD

**Issue by buysheep** [tyejae/msf.gg.public#425]
When updating DD Planner, I enter he number of items already owned and it's not saving the number and updating how many items needed, just displays 0 owned on all gear items
![Picture2MSF](https://user-images.githubusercontent.com/100708316/156203304-1ad25781-103a-4db2-94fc-73332ce32367.png)
![Picture1MSF](https://user-images.githubusercontent.com/100708316/156203309-2b4942fb-77f6-4844-94eb-f7757c229bd5.png)

**Comment by Hammerheadtime** [comment]
I was having this issue as well but it was fixed about 13 days ago.

**Comment by tyejae** [comment]
Fixed a while ago
