### ISSUE TITLE
[REQUEST]: DD5 Slider to Show Total Mats Required or Total Mats Needed (Required - Have in Inventory)

### ISSUE THREAD

**Issue by Cantholdagro** [tyejae/msf.gg.public#435]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Product

- [X] Site
- [ ] Bot

### Is your feature request related to a problem?

Currently when looking at the DD5 planner, I have to look at what the total mats required are, and then hover over the image to see how many I have, then use a calculator to determine how many I actually need.

### Describe the solution you'd like

It would be ideal to have a slider on the page to show the current view, or to show just how many I need. This way I can see the total needed without having to do all of the manual math.

You had suggested maybe adding a slider for Show Needed/Show Total back in early Feb. Just adding this here so we don't lose line of sight 

### Describe alternatives you've considered

Currently I am doing all of the math manually which is time consuming.

**Comment by tyejae** [comment]
This is done, will be live later today
![image](https://user-images.githubusercontent.com/6165105/162469742-0b10a73a-8dc5-4f73-aa8e-b0ea4c59898a.png)

**Comment by Cantholdagro** [comment]
Thanks a lot Tyejae!

**Comment by Cantholdagro** [comment]
Tyejae,

Is it just the hover over or will there be the slider as well to change the default view?

**Comment by tyejae** [comment]
@Cantholdagro It's just the hover, I didn't want to clutter up that screen by adding a slider. You can now see how much you need by hovering though. It's live on the site now.

**Comment by Cantholdagro** [comment]
No worries. Thanks for making my life easier!
