### ISSUE TITLE
[BUG] Strike Clear @Playername All command does not actually remove strikes for player

### ISSUE THREAD

**Issue by NoGood** [tyejae/msf.gg.public#439]
### I'm Not a Dummy, So I've Checked These

- [ ] It happens on multiple browsers (if site)
- [ ] I've cleared browser cache and restarted browser (if site)
- [X] I've asked support in MSF.gg Discord before writing this
- [X] I have searched the existing issues

### Product

- [ ] Site
- [X] Bot

### Current Behavior

Using ~strike clear @playername all
Gets a confirmation to remove all strikes.

Result:
All strikes all still there

### Expected Behavior

All strikes for @playername are removed 

### Steps To Reproduce

~strike clear @playername all

### Environment

```markdown
Using bot
```

**Comment by tyejae** [comment]
Thank you for reporting this. I've removed the triage and we will prioritize this as necessary.

**Comment by tyejae** [comment]
This has been replaced by the slash command `/strike clear`
