### ISSUE TITLE
[BUG] using ~strike clear @playername 1 does not always retrieve correct strike information 

### ISSUE THREAD

**Issue by NoGood** [tyejae/msf.gg.public#440]
### I'm Not a Dummy, So I've Checked These

- [ ] It happens on multiple browsers (if site)
- [ ] I've cleared browser cache and restarted browser (if site)
- [X] I've asked support in MSF.gg Discord before writing this
- [X] I have searched the existing issues

### Product

- [ ] Site
- [X] Bot

### Current Behavior

~strike clear @playername 2 doesn't always show information of the actual strike the player has received

### Expected Behavior

After using command the bot should show the correct strike as is listed in the ~strike log @playername order

### Steps To Reproduce

~strike log @playername

Bot lists multiple strikes 

~strike clear @playername 1

Bot list incorrect strike 

-
Jethro confirmed in discord that sorting or order is incorrect 

### Environment

```markdown
Bot
```

### Anything else?

![Screenshot_2022-04-16-10-25-19-01_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/412780/163671470-a83868f2-e64a-48a6-b21a-66dced026fdb.jpg)

**Comment by tyejae** [comment]
This is actually fixed using the slash command. Try `/strike clear` command. I will be deprecating the `~strike` command very soon.
