### ISSUE TITLE
[BUG] Can't edit a team on war defense, if it's in rooms 9 and 10

### ISSUE THREAD

**Issue by FatterHansen** [tyejae/msf.gg.public#442]
### I'm Not a Dummy, So I've Checked These

- [ ] It happens on multiple browsers (if site)
- [ ] I've cleared browser cache and restarted browser (if site)
- [X] I've asked support in MSF.gg Discord before writing this
- [X] I have searched the existing issues

### Product

- [X] Site
- [ ] Bot

### Current Behavior

Can't edit a team on war defense, if it's in rooms 9 and 10

### Expected Behavior

When clicking on a toon, it should disappear, but it doesn't. Move the whole team to room 8, and it's editable.

### Steps To Reproduce

War Defense in Alliance page.
Move to room 9 or 10 by using the slider.
Click edit
Click on a toon

### Environment

```markdown
- Device: Desktop
- OS: Windows 11
- Browser: Chrome
- Version: Version 100.0.4896.127 (Officiel version) (64-bit)
```

### Anything else?

https://discord.com/channels/455443542358360064/698036394601218098/969607094753972235

**Comment by tyejae** [comment]
Fixed and live
