### ISSUE TITLE
[BUG] Shuri ultimate missing energy pips

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#445]
### I'm Not a Dummy, So I've Checked These

- [X] It happens on multiple browsers (if site)
- [X] I've cleared browser cache and restarted browser (if site)
- [X] I've asked support in MSF.gg Discord before writing this
- [X] I have searched the existing issues

### Product

- [X] Site
- [X] Bot

### Current Behavior

Shuri's ultimate description is missing the energy pips. It should be showing 0/4 pips, but it doesn't show any pips at all. This appears to be affecting any ability that starts with 0 energy. Another example is Night Nurse's ultimate at level 6 or lower.

Site:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/11431194/168743585-c1340724-5560-465d-9880-ddb0e929ef37.png">

<img width="569" alt="image" src="https://user-images.githubusercontent.com/11431194/168743621-53ddde51-acd6-42d2-854e-c14f9c15f043.png">

Bot:
<img width="442" alt="image" src="https://user-images.githubusercontent.com/11431194/168743670-352fd0d9-ba12-44b0-a41c-ce95da95c5dc.png">

### Expected Behavior

It should be showing empty pips for the amount of energy that the ability requires
<img width="573" alt="image" src="https://user-images.githubusercontent.com/11431194/168745207-db5605c6-d6b7-47a3-ad4b-c0431890fc70.png">

### Steps To Reproduce

Site:
1. Navigate to Shuri's character page
2. Observe that her ultimate doesn't have energy pips

Bot:
1. use `ch shuri u` command
2. Notice that the description does not have energy pips

### Environment

```markdown
- Device: 
- OS: 
- Browser: 
- Version:
```

**Comment by tyejae** [comment]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/6165105/172882271-6a5f049b-09d7-4323-836f-a64b651b7119.png">
