### ISSUE TITLE
[BUG] I’ve tried to reset my password for msf.gg, but it sends no email. I also tried to see if the reset username email would show up, that doesn’t either.

### ISSUE THREAD

**Issue by Enderghast77** [tyejae/msf.gg.public#446]
### I'm Not a Dummy, So I've Checked These

- [ ] It happens on multiple browsers (if site)
- [ ] I've cleared browser cache and restarted browser (if site)
- [X] I've asked support in MSF.gg Discord before writing this
- [X] I have searched the existing issues

### Product

- [X] Site
- [ ] Bot

### Current Behavior

Basically as it says in the title. I tried to reset my password because I forgot it, it says it’s sending one to me, but it doesn’t show up after 10+ minutes of waiting. Same for the username.

### Expected Behavior

I expected to get reset emails.

### Steps To Reproduce

1. Go to Log In
2. Go to Account Recovery
3. Input your email
4. Click reset password or reset username

### Environment

```markdown
- Device: Iphone SE
- OS: 
- Browser: Safari
- Version: 15.4.1
```

**Comment by tyejae** [comment]
What is your username? I will send you an email with your reset link.

**Comment by tyejae** [comment]
Sent a reset email manually. You should have a message from accounts@msf.gg. Please check your inbox and spam folders.
