### ISSUE TITLE
[REQUEST]: Login Check for "Team Builder"

### ISSUE THREAD

**Issue by GHosaPhat** [tyejae/msf.gg.public#448]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Product

- [X] Site
- [ ] Bot

### Is your feature request related to a problem?

The "Build Team" link tries to load the current user's existing teams. If the user isn't logged in, it just shows a blank page.
![image](https://user-images.githubusercontent.com/13453101/170838629-02b2df53-099e-494d-8779-63b6004fdff6.png)

### Describe the solution you'd like

If the user isn't logged in, maybe show a "You Need To Be Logged In To Use This Feature" message instead.

### Anything else?

https://discord.com/channels/455443542358360064/702225744180412497/980173557600485407

**Comment by tyejae** [comment]
This is fixed
![image](https://user-images.githubusercontent.com/6165105/172895345-4e9bda00-27ce-4f88-b6c7-db80eb1abe60.png)
![image](https://user-images.githubusercontent.com/6165105/172895400-4e528f44-0c61-4311-8d99-b5ef54ff9041.png)
