### ISSUE TITLE
[BUG] ISO-8 Matrix Color Doesn't Populate In Gear & Stats Page

### ISSUE THREAD

**Issue by GHosaPhat** [tyejae/msf.gg.public#449]
### I'm Not a Dummy, So I've Checked These

- [X] It happens on multiple browsers (if site)
- [X] I've cleared browser cache and restarted browser (if site)
- [X] I've asked support in MSF.gg Discord before writing this
- [X] I have searched the existing issues

### Product

- [X] Site
- [ ] Bot

### Current Behavior

Reported by user **fShark**: when clicking "Load My Character" button on Character's Gear & Status, the ISO Color is not being loaded.

![image](https://user-images.githubusercontent.com/13453101/171044946-3933bea1-8b78-493f-b2cb-2529e0e34823.png)

### Expected Behavior

The "**Load My Character**" button on the "**Gear & Stats**" page should populate the ISO Matix color from what is selected in the player's roster.

### Steps To Reproduce

1. Select a character on the **My Roster** page and update their ISO Matrix to Blue
2. Go to the **My Roster Stats** tab
3. Select the character that was just updated
4. Go to the **Gear & Stats** tab and click **Load My Character**
5. Other stats appear to populate correctly except for the ISO Matrix

### Environment

```markdown
- Device: Laptop
- OS: Windows 11
- Browser: Microsoft Edge
- Version: Version 101.0.1210.53 (Official build) (64-bit)
```

**Comment by tyejae** [comment]
Thank you. I'll be looking into this shortly

**Comment by tyejae** [comment]
Fixed will be live later today
