### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by StratosSpawn** [tyejae/msf.gg.public#45]
Empyrialist, PimpToxie, & TyeJae,
I have been trying to register on the msf.gg site, but after I enter all of my information and click the register button, I simply see a red bar show up below the title bar, without any text in it.  Is there an issue with registering on the site, or could there be something else going on?
![msf gg registration issue](https://user-images.githubusercontent.com/48249275/53810310-a7e9ca00-3f24-11e9-970c-ea592efae719.png)

**Comment by tyejae** [comment]
Can you please contact me on Discord so we can try to get this resolved for you? You can reach me directly at tyejae#2513

This way you won't have to post personal information here.

**Comment by Usher87** [comment]
I'm having the same problem. Are there any solutions already?

**Comment by tyejae** [comment]
closing because no one ever reached out to me on Discord
