### ISSUE TITLE
[REQUEST]: Add room 9 and 10 in war defense

### ISSUE THREAD

**Issue by clement-michelet** [tyejae/msf.gg.public#465]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Product

- [X] Site
- [ ] Bot

### Is your feature request related to a problem?

New rooms (9 and 10) were added a moment ago.
The bot command rely on defense to show if a team is available. With those two new rooms, 2 teams are not marked as in defense.

### Describe the solution you'd like

Add room 9 and 10 to allow configuration

**Comment by GHosaPhat** [comment]
They are there and have been since they were added to the game, but you have to scroll over to edit them and the scroll bar can be a little hard to see sometimes. It's been suggested that the color of the scrollbar be changed to make it a little more visible.

**Comment by clement-michelet** [comment]
Thank you for the clarification
