### ISSUE TITLE
STRIKE raid beta issues

### ISSUE THREAD

**Issue by DCrisman** [tyejae/msf.gg.public#47]
The STRIKE beta raid isn't parsing correctly.  It shows a blank wave and doesn't seem to be able to determine enemy position following that.
![image](https://user-images.githubusercontent.com/14947484/53826955-b50bb680-3f2e-11e9-9b45-a15b24e81532.png)

**Comment by tyejae** [comment]
FoxNext took away wave info from us. Closing this issue as it no longer applies.
