### ISSUE TITLE
Saved Teams not showing up

### ISSUE THREAD

**Issue by WushuMonk** [tyejae/msf.gg.public#48]
I have made several teams using the below steps.

Logged in
Go to Characters Screen and select Build Team
Select 5 characters (DD/IF/LC/JJ/Pun)
Hit Go
Select Save Team
Enter Team name (Defenders)
Hit Done
Actual Result: Get a screen that says "You don't have any teams! To create a team, go to Characters and Press Build Team"

Expected Result: Team that was created is displayed here.

I have tried on multiple browsers, multiple computers with same result

**Comment by tyejae** [comment]
This should now be resolved. Please contact me again if you continue to have issues.
