### ISSUE TITLE
Mutant Origin

### ISSUE THREAD

**Issue by TheBooGhost** [tyejae/msf.gg.public#5]
There's no option on the left of the characters tab to sort by mutants.

**Comment by TheBooGhost** [comment]
Unless it should be in the Flavor tab, and if that's the case, Inhuman should be moved to Flavor as well if we're following the way they're presented in game.

**Comment by tyejae** [comment]
Done!

![image](https://user-images.githubusercontent.com/6165105/41488863-ae331b4c-70a2-11e8-9970-f92b805e1e57.png)


This will go out in the next patch to the site
