### ISSUE TITLE
Killmonger's kit not visible

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#50]
Looks like there's an issue parsing his kit's description?

![image](https://user-images.githubusercontent.com/11431194/54104900-a68a2880-438e-11e9-97fe-b023e37c041c.png)

**Comment by tyejae** [comment]
Fixed, it's now live. I just needed to find some time. I was able to do this today.

![image](https://user-images.githubusercontent.com/6165105/54329793-847fe880-45d0-11e9-8884-747ad08feaca.png)
