### ISSUE TITLE
Ant-Man's Team-up, wrong values.

### ISSUE THREAD

**Issue by SirAwful** [tyejae/msf.gg.public#51]
Ant-Man's Ultimate ability currently reads "If Wasp is an ally, deal an additional +170% damage to all targets" When it should read "If Wasp is an ally, deal an additional +30% damage to all targets"

It makes it seem like the Team-Up make his Ultimate do crazy damage, when in reality it just boosts it a little bit.

**Comment by tyejae** [comment]
Good catch. My script isn't subtracting the value correctly. I'll see about correcting this soon.

**Comment by tyejae** [comment]
Fixed, publishing to the site now.

![image](https://user-images.githubusercontent.com/6165105/54329834-a11c2080-45d0-11e9-89f4-f0588a744063.png)
