### ISSUE TITLE
Ability Descriptions not Parsed correctly

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#52]
Got some good ol' [object object] going on
![image](https://user-images.githubusercontent.com/11431194/55358876-4a925b80-5485-11e9-99c0-457a41e68616.png)

**Comment by tyejae** [comment]
This is fixed and will be pushed live soon

![image](https://user-images.githubusercontent.com/6165105/55746094-b62c7980-59ed-11e9-8ff4-318f4a44a791.png)

**Comment by chronolinq** [comment]
One more instance:

![image](https://user-images.githubusercontent.com/11431194/55750399-0ad4f200-59f8-11e9-9298-18582996178f.png)

**Comment by tyejae** [comment]
Reopening to fix new findings.... I swear I looked at her's... lol

**Comment by tyejae** [comment]
Fixed, will be live soon

![image](https://user-images.githubusercontent.com/6165105/55757096-01538600-5a08-11e9-8110-890158d5e874.png)
