### ISSUE TITLE
Okoye is missing Focus increase on L7 assist

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#57]
![image](https://user-images.githubusercontent.com/11431194/56979087-c8ea2800-6b2d-11e9-9904-430e5338cbcf.png)
![image](https://user-images.githubusercontent.com/11431194/56979108-d7384400-6b2d-11e9-8d00-d0c31d9e481d.png)

**Comment by tyejae** [comment]
Actually also missing the % change to remove a buff

**Comment by tyejae** [comment]
This is building and will be published soon.
