### ISSUE TITLE
Kree

### ISSUE THREAD

**Issue by TheBooGhost** [tyejae/msf.gg.public#6]
Should Kree be moved to Flavor along with Mutant and Inhuman? Just noticed it was in the Team tab.

**Comment by tyejae** [comment]
Yeah I think you're right. I'll move it. They are a race, not a team

**Comment by tyejae** [comment]
Done!

![image](https://user-images.githubusercontent.com/6165105/41498507-8171493a-7124-11e8-9216-eb8ae4a8963d.png)

This will go out with the next release to the site
