### ISSUE TITLE
Min button on gear tier inspector

### ISSUE THREAD

**Issue by Abepena** [tyejae/msf.gg.public#66]
The min button on the gear tier inspector does not change the total gear needed for the tier.

![D972465C-2332-4757-BFDE-82F305982A7A](https://user-images.githubusercontent.com/29493747/58384518-76771c80-7fb0-11e9-8842-268a9859ce85.png)

The image above shows mats needed for tier 12 when it should show the mats needed for tier 1 after hitting the min button.

**Comment by tyejae** [comment]
Fixed. Building now, and will be publishing soon. Thanks!
