### ISSUE TITLE
msf.pal.gg fail csv upload

### ISSUE THREAD

**Issue by 7h0ki3** [tyejae/msf.gg.public#69]
Does not allow me to upload csv to update roster

Save button remains grayed out.

https://cdn.discordapp.com/attachments/596552689714855944/597835029128806415/unknown.png

**Comment by chronolinq** [comment]
@7h0ki3 This issue tracker is for msf.gg, not msf.pal.gg. You can join this discord server for questions about msf.pal.gg: https://discord.gg/etSFCg

**Comment by tyejae** [comment]
Thanks @chronolinq
