### ISSUE TITLE
Wolverine

### ISSUE THREAD

**Issue by TheBooGhost** [tyejae/msf.gg.public#7]
Wolverine's Crit Chance should be 20%. It's listed at 10% on the Stats tab.

**Comment by tyejae** [comment]
This is now fixed and will go out in the next push to the site. Thanks again Boo

![image](https://user-images.githubusercontent.com/6165105/41680927-e486d2b8-7487-11e8-8d64-b3a4a1670c04.png)

**Comment by tyejae** [comment]
This is live now
