### ISSUE TITLE
Archived raid node links are broken

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#71]
It looks like the url structure has changed for the raid nodes. e.g.

Alpha IV Node A7

Live:
https://msf.gg/maps/raid_alpha_d/A7/evr_boss_bp_mb_d04_l72_v01
Archive:
http://msf.tyejae.com/maps/evr_boss_bp_mb_d04_l72_v01/A7/raidId
Actual?
http://msf.tyejae.com/maps/raid_alpha_d/A7/evr_boss_bp_mb_d04_l72_v01

**Comment by tyejae** [comment]
I just linked to the archived site now. I can't keep up with all the FoxNext changes.
