### ISSUE TITLE
Ant man synergy bug

### ISSUE THREAD

**Issue by tyejae** [tyejae/msf.gg.public#75]
![5E9FE36D-E432-4B75-BF26-9245B0A496E4](https://user-images.githubusercontent.com/6165105/62561076-44492d00-b833-11e9-9137-d233b6dc75e7.jpeg)

Ant-Man’s %15 Team-Up doesn’t apply to Ultron and Minn-Erva

**Comment by chronolinq** [comment]
@tyejae Ant-Man's team up only applies to Heroes
![image](https://user-images.githubusercontent.com/11431194/62574473-6bacf380-b84d-11e9-8f0a-9ee88f4e08e5.png)

**Comment by tyejae** [comment]
Forgot about that... thanks. Closing this.
