### ISSUE TITLE
Google sheets / ImportHTML doesnt import every character

### ISSUE THREAD

**Issue by cptngorgutz** [tyejae/msf.gg.public#76]
For instance using =IMPORTHTML("https://msf.gg/hero-total-stats","table",1)

only outputs around 99 characters

im assuming the html isnt done properly or something or certain characters are being hidden
such as 
    Agent Coulson

    America Chavez

    Captain Marvel

    Carnage

    Colossus

    Cyclops

    Falcon

    Green Goblin

    Juggernaut

    Killmonger

    M'Baku

    Magneto

    Mantis

    Minn-Erva

    Mysterio

    Phoenix

    Psylocke

    Pyro

    Rescue

    Rhino

    Shocker

    Shuri

    Spider-Man (Miles)

    Vulture

    War Machine

**Comment by tyejae** [comment]
I just looked at the table structure. It's the same structure for the ones that are importing and the ones that are not importing. This looks to be something out of my control with the google sheets function. I do have an export to CSV function on that page though if you need to get the data. 

Closing this issue.
