### ISSUE TITLE
Stat table hover highlight hard to read

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#77]
Alternating color alternates to a which bg with white text
![image](https://user-images.githubusercontent.com/11431194/62685322-4d431700-b977-11e9-8fe7-ae3de927f4f9.png)

**Comment by tyejae** [comment]
Fixed

**Comment by chronolinq** [comment]
Back at it again with the latest version
![image](https://user-images.githubusercontent.com/11431194/82965410-e5e56a80-9f7c-11ea-9a4d-51229c2d7f30.png)
