### ISSUE TITLE
Ultimus III Raid is missing node H6

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#79]
Node is not being rendered
![image](https://user-images.githubusercontent.com/11431194/62970544-9c000f00-bdc4-11e9-86b9-dd9e67ed8dac.png)

**Comment by tyejae** [comment]
Fixed, will be live with next update
![image](https://user-images.githubusercontent.com/6165105/63187833-ab759700-c014-11e9-8e46-8cb349b9d4ae.png)
