### ISSUE TITLE
Responsive layout too wide on PCs

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#83]
Low pri, but can we get a max-width some pages like the character detail page? It's a little jarring to see some screens when my browser is full width

![image](https://user-images.githubusercontent.com/11431194/63202149-3e2a2c00-c03d-11e9-975d-b38182f486ac.png)

**Comment by tyejae** [comment]
Since I've added two more columns, I don't feel it's as jarring
![image](https://user-images.githubusercontent.com/6165105/86523716-0d094480-be25-11ea-90f0-fee5a970238c.png)
