### ISSUE TITLE
Challenge & Event Rewards

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#9]
Some of this information might be hard to capture, but it would be nice if the challenges and Events listed the rewards for each tier. Would help newer players see the value between tiers and serve as a reference guide without having to open the game.  Also since this information is not always available (events go away) it would help when the events aren't active.

**Comment by chronolinq** [comment]
This is answered on the front page. I'm guessing the information for the page is directly driven from data gathered from the game? Would be nice if this information was added though imo.

**Comment by tyejae** [comment]
I’ll take a look at this when the next patch goes out. We will continue to check for new data
