### ISSUE TITLE
Raid Map UX

### ISSUE THREAD

**Issue by chronolinq** [tyejae/msf.gg.public#93]
- [ ] Raid lanes show up on the map a little inconsistently. In the image below, the leftmost 2 lanes and the rightmost two lanes are rendered differently (left has a gap). This is because there was another line on the left that was deleted. It would be awsome if there was a clean up step that consolidated raid lines
![image](https://user-images.githubusercontent.com/11431194/64983395-3ac0d500-d875-11e9-9fd1-6f5bbbd2d34b.png)
- [ ] When picking a color on the right side, it would be nice if it highlighted the colors on the palette picker that are in use on the map
![image](https://user-images.githubusercontent.com/11431194/64983576-ac991e80-d875-11e9-98fd-0b4340418e52.png)
- [ ] Another convenience would be the ability to copy the raid lanes from one strike team to another

**Comment by tyejae** [comment]
All of these have been done
