### ISSUE TITLE
PNG Support

### ISSUE THREAD

**Issue by Kjnava** [tyejae/msf.gg.public#94]
https://msf.gg/character_images/AimDmg_Speed.png support missing for the following characters

Coulson
AmericaChavez
CaptainMarvel
Colossus
Cyclops
HumanTorch
Killmonger
MBaku
Minerva
MrFantastic
Mysterio
MysterioMinion
Namor
Phoenix
Psylocke
Rescue
Rhino
Shocker
Shuri
Thing
Vulture

**Comment by tyejae** [comment]
Added all these, along with Beast and Hela!
