### ISSUE TITLE
SHIELD Security Passive Text

### ISSUE THREAD

**Issue by tyejae** [tyejae/msf.gg.public#97]
It says WAR OFFENSE on colson on sec passive?

![D40B7A6B-D874-46BA-86A3-79DD49BC02B2](https://user-images.githubusercontent.com/6165105/65426581-55d79b80-ddc5-11e9-94d5-d9a5e191278e.jpeg)

**Comment by chronolinq** [comment]
They must have patched it real quick. Update to latest should do the trick
![image](https://user-images.githubusercontent.com/11431194/65450029-1b83f380-ddf1-11e9-86d5-bf92121222eb.png)

**Comment by tyejae** [comment]
The latest patch from FoxNext fixed this. Closing.
