### ISSUE TITLE
Improvement : My Teams Screen - Allow to display characters that are not already in a team

### ISSUE THREAD

**Issue by sylvainbruas** [tyejae/msf.gg.public#99]
Hi,

It would be great to a filter to display only characters that are not already attached to a team.
There are more that 100 characters, the list is quite small, so it's not easy to keep track of all team contents.

Thanks for your help

**Comment by tyejae** [comment]
![image](https://user-images.githubusercontent.com/6165105/69667001-6f59c580-104a-11ea-9053-87f09b4aa085.png)
Good idea. I implemented this today.  I will be publishing this change later tonight. I also implemented a way to display them all again.
